//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Enum_AllocationMode_Activity {
            get {
                return ResourceManager.GetString("Enum_AllocationMode_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string Enum_AllocationMode_Billing {
            get {
                return ResourceManager.GetString("Enum_AllocationMode_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Enum_AllocationMode_Cost {
            get {
                return ResourceManager.GetString("Enum_AllocationMode_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effort.
        /// </summary>
        public static string Enum_AllocationMode_Effort {
            get {
                return ResourceManager.GetString("Enum_AllocationMode_Effort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Enum_AnnotationStyle_Color {
            get {
                return ResourceManager.GetString("Enum_AnnotationStyle_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_AnnotationStyle_None {
            get {
                return ResourceManager.GetString("Enum_AnnotationStyle_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain.
        /// </summary>
        public static string Enum_AnnotationStyle_Plain {
            get {
                return ResourceManager.GetString("Enum_AnnotationStyle_Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Enum_DisplayStyle_Block {
            get {
                return ResourceManager.GetString("Enum_DisplayStyle_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slanted.
        /// </summary>
        public static string Enum_DisplayStyle_Slanted {
            get {
                return ResourceManager.GetString("Enum_DisplayStyle_Slanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_GroupByMode_None {
            get {
                return ResourceManager.GetString("Enum_GroupByMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string Enum_GroupByMode_Resource {
            get {
                return ResourceManager.GetString("Enum_GroupByMode_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Stream.
        /// </summary>
        public static string Enum_GroupByMode_WorkStream {
            get {
                return ResourceManager.GetString("Enum_GroupByMode_WorkStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        public static string Enum_InterActivityAllocationType_Direct {
            get {
                return ResourceManager.GetString("Enum_InterActivityAllocationType_Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect.
        /// </summary>
        public static string Enum_InterActivityAllocationType_Indirect {
            get {
                return ResourceManager.GetString("Enum_InterActivityAllocationType_Indirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_InterActivityAllocationType_None {
            get {
                return ResourceManager.GetString("Enum_InterActivityAllocationType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND (Enabled).
        /// </summary>
        public static string Enum_LogicalOperator_ACTIVE_AND {
            get {
                return ResourceManager.GetString("Enum_LogicalOperator_ACTIVE_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string Enum_LogicalOperator_AND {
            get {
                return ResourceManager.GetString("Enum_LogicalOperator_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Enum_LogicalOperator_OR {
            get {
                return ResourceManager.GetString("Enum_LogicalOperator_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined.
        /// </summary>
        public static string Enum_ScheduleMode_Combined {
            get {
                return ResourceManager.GetString("Enum_ScheduleMode_Combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string Enum_ScheduleMode_Scheduled {
            get {
                return ResourceManager.GetString("Enum_ScheduleMode_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unscheduled.
        /// </summary>
        public static string Enum_ScheduleMode_Unscheduled {
            get {
                return ResourceManager.GetString("Enum_ScheduleMode_Unscheduled", resourceCulture);
            }
        }
    }
}
