//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Enum_AllocationMode_Activity {
            get {
                return ResourceManager.GetString("Enum_AllocationMode_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string Enum_AllocationMode_Billing {
            get {
                return ResourceManager.GetString("Enum_AllocationMode_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Enum_AllocationMode_Cost {
            get {
                return ResourceManager.GetString("Enum_AllocationMode_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effort.
        /// </summary>
        public static string Enum_AllocationMode_Effort {
            get {
                return ResourceManager.GetString("Enum_AllocationMode_Effort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Enum_AnnotationStyle_Color {
            get {
                return ResourceManager.GetString("Enum_AnnotationStyle_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_AnnotationStyle_None {
            get {
                return ResourceManager.GetString("Enum_AnnotationStyle_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain.
        /// </summary>
        public static string Enum_AnnotationStyle_Plain {
            get {
                return ResourceManager.GetString("Enum_AnnotationStyle_Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponential.
        /// </summary>
        public static string Enum_CurveFittingType_Exponential {
            get {
                return ResourceManager.GetString("Enum_CurveFittingType_Exponential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string Enum_CurveFittingType_Linear {
            get {
                return ResourceManager.GetString("Enum_CurveFittingType_Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithmic.
        /// </summary>
        public static string Enum_CurveFittingType_Logarithmic {
            get {
                return ResourceManager.GetString("Enum_CurveFittingType_Logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_CurveFittingType_None {
            get {
                return ResourceManager.GetString("Enum_CurveFittingType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomial (2nd order).
        /// </summary>
        public static string Enum_CurveFittingType_PolynomialOrder2 {
            get {
                return ResourceManager.GetString("Enum_CurveFittingType_PolynomialOrder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomial (3rd order).
        /// </summary>
        public static string Enum_CurveFittingType_PolynomialOrder3 {
            get {
                return ResourceManager.GetString("Enum_CurveFittingType_PolynomialOrder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomial (4th order).
        /// </summary>
        public static string Enum_CurveFittingType_PolynomialOrder4 {
            get {
                return ResourceManager.GetString("Enum_CurveFittingType_PolynomialOrder4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Enum_CurveFittingType_Power {
            get {
                return ResourceManager.GetString("Enum_CurveFittingType_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Enum_DisplayStyle_Block {
            get {
                return ResourceManager.GetString("Enum_DisplayStyle_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slanted.
        /// </summary>
        public static string Enum_DisplayStyle_Slanted {
            get {
                return ResourceManager.GetString("Enum_DisplayStyle_Slanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_GroupByMode_None {
            get {
                return ResourceManager.GetString("Enum_GroupByMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string Enum_GroupByMode_Resource {
            get {
                return ResourceManager.GetString("Enum_GroupByMode_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Stream.
        /// </summary>
        public static string Enum_GroupByMode_WorkStream {
            get {
                return ResourceManager.GetString("Enum_GroupByMode_WorkStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        public static string Enum_InterActivityAllocationType_Direct {
            get {
                return ResourceManager.GetString("Enum_InterActivityAllocationType_Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect.
        /// </summary>
        public static string Enum_InterActivityAllocationType_Indirect {
            get {
                return ResourceManager.GetString("Enum_InterActivityAllocationType_Indirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_InterActivityAllocationType_None {
            get {
                return ResourceManager.GetString("Enum_InterActivityAllocationType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND (Enabled).
        /// </summary>
        public static string Enum_LogicalOperator_ACTIVE_AND {
            get {
                return ResourceManager.GetString("Enum_LogicalOperator_ACTIVE_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string Enum_LogicalOperator_AND {
            get {
                return ResourceManager.GetString("Enum_LogicalOperator_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Enum_LogicalOperator_OR {
            get {
                return ResourceManager.GetString("Enum_LogicalOperator_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined.
        /// </summary>
        public static string Enum_ScheduleMode_Combined {
            get {
                return ResourceManager.GetString("Enum_ScheduleMode_Combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string Enum_ScheduleMode_Scheduled {
            get {
                return ResourceManager.GetString("Enum_ScheduleMode_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unscheduled.
        /// </summary>
        public static string Enum_ScheduleMode_Unscheduled {
            get {
                return ResourceManager.GetString("Enum_ScheduleMode_Unscheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Billing.
        /// </summary>
        public static string Enum_TrackedMetric_BillingsDirect {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_BillingsDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Billing.
        /// </summary>
        public static string Enum_TrackedMetric_BillingsIndirect {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_BillingsIndirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Billing.
        /// </summary>
        public static string Enum_TrackedMetric_BillingsOther {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_BillingsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Billing.
        /// </summary>
        public static string Enum_TrackedMetric_BillingsTotal {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_BillingsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Cost.
        /// </summary>
        public static string Enum_TrackedMetric_CostsDirect {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_CostsDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Cost.
        /// </summary>
        public static string Enum_TrackedMetric_CostsIndirect {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_CostsIndirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Cost.
        /// </summary>
        public static string Enum_TrackedMetric_CostsOther {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_CostsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string Enum_TrackedMetric_CostsTotal {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_CostsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Effort.
        /// </summary>
        public static string Enum_TrackedMetric_EffortsActivity {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_EffortsActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Effort.
        /// </summary>
        public static string Enum_TrackedMetric_EffortsDirect {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_EffortsDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Enum_TrackedMetric_EffortsEfficiency {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_EffortsEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Effort.
        /// </summary>
        public static string Enum_TrackedMetric_EffortsIndirect {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_EffortsIndirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Effort.
        /// </summary>
        public static string Enum_TrackedMetric_EffortsOther {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_EffortsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Effort.
        /// </summary>
        public static string Enum_TrackedMetric_EffortsTotal {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_EffortsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Margin.
        /// </summary>
        public static string Enum_TrackedMetric_MarginsDirect {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_MarginsDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Abs. Margin.
        /// </summary>
        public static string Enum_TrackedMetric_MarginsDirectAbsolute {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_MarginsDirectAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Margin.
        /// </summary>
        public static string Enum_TrackedMetric_MarginsIndirect {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_MarginsIndirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Abs. Margin.
        /// </summary>
        public static string Enum_TrackedMetric_MarginsIndirectAbsolute {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_MarginsIndirectAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Margin.
        /// </summary>
        public static string Enum_TrackedMetric_MarginsOther {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_MarginsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Abs. Margin.
        /// </summary>
        public static string Enum_TrackedMetric_MarginsOtherAbsolute {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_MarginsOtherAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Margin.
        /// </summary>
        public static string Enum_TrackedMetric_MarginsTotal {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_MarginsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Abs. Margin.
        /// </summary>
        public static string Enum_TrackedMetric_MarginsTotalAbsolute {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_MarginsTotalAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic Complexity.
        /// </summary>
        public static string Enum_TrackedMetric_NetworkCyclomaticComplexity {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_NetworkCyclomaticComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (days).
        /// </summary>
        public static string Enum_TrackedMetric_NetworkDuration {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_NetworkDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (months).
        /// </summary>
        public static string Enum_TrackedMetric_NetworkDurationManMonths {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_NetworkDurationManMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_TrackedMetric_None {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Risk.
        /// </summary>
        public static string Enum_TrackedMetric_RisksActivity {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_RisksActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Risk (with Std Dev).
        /// </summary>
        public static string Enum_TrackedMetric_RisksActivityStdDevCorrection {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_RisksActivityStdDevCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticality Risk.
        /// </summary>
        public static string Enum_TrackedMetric_RisksCriticality {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_RisksCriticality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci Risk.
        /// </summary>
        public static string Enum_TrackedMetric_RisksFibonacci {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_RisksFibonacci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Activity Risk.
        /// </summary>
        public static string Enum_TrackedMetric_RisksGeometricActivity {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_RisksGeometricActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Criticality Risk.
        /// </summary>
        public static string Enum_TrackedMetric_RisksGeometricCriticality {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_RisksGeometricCriticality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Fibonacci Risk.
        /// </summary>
        public static string Enum_TrackedMetric_RisksGeometricFibonacci {
            get {
                return ResourceManager.GetString("Enum_TrackedMetric_RisksGeometricFibonacci", resourceCulture);
            }
        }
    }
}
