//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Filters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Filters", typeof(Filters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Filter_ExcelFileType {
            get {
                return ResourceManager.GetString("Filter_ExcelFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.xlsx.
        /// </summary>
        public static string Filter_ExcelXlsxFilePattern {
            get {
                return ResourceManager.GetString("Filter_ExcelXlsxFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graphml.
        /// </summary>
        public static string Filter_GraphMLFileExtension {
            get {
                return ResourceManager.GetString("Filter_GraphMLFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.graphml.
        /// </summary>
        public static string Filter_GraphMLFilePattern {
            get {
                return ResourceManager.GetString("Filter_GraphMLFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphML.
        /// </summary>
        public static string Filter_GraphMLFileType {
            get {
                return ResourceManager.GetString("Filter_GraphMLFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dot.
        /// </summary>
        public static string Filter_GraphVizFileExtension {
            get {
                return ResourceManager.GetString("Filter_GraphVizFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.dot.
        /// </summary>
        public static string Filter_GraphVizFilePattern {
            get {
                return ResourceManager.GetString("Filter_GraphVizFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphViz.
        /// </summary>
        public static string Filter_GraphVizFileType {
            get {
                return ResourceManager.GetString("Filter_GraphVizFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmp.
        /// </summary>
        public static string Filter_ImageBmpFileExtension {
            get {
                return ResourceManager.GetString("Filter_ImageBmpFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP Image.
        /// </summary>
        public static string Filter_ImageBmpFileType {
            get {
                return ResourceManager.GetString("Filter_ImageBmpFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Filter_ImageFileType {
            get {
                return ResourceManager.GetString("Filter_ImageFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gif.
        /// </summary>
        public static string Filter_ImageGifFileExtension {
            get {
                return ResourceManager.GetString("Filter_ImageGifFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Image.
        /// </summary>
        public static string Filter_ImageGifFileType {
            get {
                return ResourceManager.GetString("Filter_ImageGifFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jpeg.
        /// </summary>
        public static string Filter_ImageJpegFileExtension {
            get {
                return ResourceManager.GetString("Filter_ImageJpegFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.jpeg.
        /// </summary>
        public static string Filter_ImageJpegFilePattern {
            get {
                return ResourceManager.GetString("Filter_ImageJpegFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Image.
        /// </summary>
        public static string Filter_ImageJpegFileType {
            get {
                return ResourceManager.GetString("Filter_ImageJpegFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png.
        /// </summary>
        public static string Filter_ImagePngFileExtension {
            get {
                return ResourceManager.GetString("Filter_ImagePngFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.png.
        /// </summary>
        public static string Filter_ImagePngFilePattern {
            get {
                return ResourceManager.GetString("Filter_ImagePngFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Image.
        /// </summary>
        public static string Filter_ImagePngFileType {
            get {
                return ResourceManager.GetString("Filter_ImagePngFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to svg.
        /// </summary>
        public static string Filter_ImageSvgFileExtension {
            get {
                return ResourceManager.GetString("Filter_ImageSvgFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.svg.
        /// </summary>
        public static string Filter_ImageSvgFilePattern {
            get {
                return ResourceManager.GetString("Filter_ImageSvgFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVG Image.
        /// </summary>
        public static string Filter_ImageSvgFileType {
            get {
                return ResourceManager.GetString("Filter_ImageSvgFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Project.
        /// </summary>
        public static string Filter_MicrosoftProjectFileType {
            get {
                return ResourceManager.GetString("Filter_MicrosoftProjectFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpp.
        /// </summary>
        public static string Filter_MicrosoftProjectMppFileExtension {
            get {
                return ResourceManager.GetString("Filter_MicrosoftProjectMppFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.mpp.
        /// </summary>
        public static string Filter_MicrosoftProjectMppFilePattern {
            get {
                return ResourceManager.GetString("Filter_MicrosoftProjectMppFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        public static string Filter_MicrosoftProjectXmlFileExtension {
            get {
                return ResourceManager.GetString("Filter_MicrosoftProjectXmlFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.xml.
        /// </summary>
        public static string Filter_MicrosoftProjectXmlFilePattern {
            get {
                return ResourceManager.GetString("Filter_MicrosoftProjectXmlFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pdf.
        /// </summary>
        public static string Filter_PdfFileExtension {
            get {
                return ResourceManager.GetString("Filter_PdfFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.pdf.
        /// </summary>
        public static string Filter_PdfFilePattern {
            get {
                return ResourceManager.GetString("Filter_PdfFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string Filter_PdfFileType {
            get {
                return ResourceManager.GetString("Filter_PdfFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zpp.
        /// </summary>
        public static string Filter_ProjectPlanFileExtension {
            get {
                return ResourceManager.GetString("Filter_ProjectPlanFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.zpp.
        /// </summary>
        public static string Filter_ProjectPlanFilePattern {
            get {
                return ResourceManager.GetString("Filter_ProjectPlanFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectplan.net.
        /// </summary>
        public static string Filter_ProjectPlanFileType {
            get {
                return ResourceManager.GetString("Filter_ProjectPlanFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xlsx.
        /// </summary>
        public static string Filter_ProjectXlsxFileExtension {
            get {
                return ResourceManager.GetString("Filter_ProjectXlsxFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.xlsx.
        /// </summary>
        public static string Filter_ProjectXlsxFilePattern {
            get {
                return ResourceManager.GetString("Filter_ProjectXlsxFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Filter_ProjectXlsxFileType {
            get {
                return ResourceManager.GetString("Filter_ProjectXlsxFileType", resourceCulture);
            }
        }
    }
}
