//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Filters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Filters", typeof(Filters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mpp.
        /// </summary>
        public static string ImportMicrosoftProjectFileExtension {
            get {
                return ResourceManager.GetString("ImportMicrosoftProjectFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Project.
        /// </summary>
        public static string ImportMicrosoftProjectFileType {
            get {
                return ResourceManager.GetString("ImportMicrosoftProjectFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        public static string ImportMicrosoftProjectXMLFileExtension {
            get {
                return ResourceManager.GetString("ImportMicrosoftProjectXMLFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Project XML.
        /// </summary>
        public static string ImportMicrosoftProjectXMLFileType {
            get {
                return ResourceManager.GetString("ImportMicrosoftProjectXMLFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        public static string ImportProjectJsonFileExtension {
            get {
                return ResourceManager.GetString("ImportProjectJsonFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Json.
        /// </summary>
        public static string ImportProjectJsonFileType {
            get {
                return ResourceManager.GetString("ImportProjectJsonFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .zpp.
        /// </summary>
        public static string OpenProjectPlanFileExtension {
            get {
                return ResourceManager.GetString("OpenProjectPlanFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Plan.
        /// </summary>
        public static string OpenProjectPlanFileType {
            get {
                return ResourceManager.GetString("OpenProjectPlanFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv.
        /// </summary>
        public static string SaveCsvFileExtension {
            get {
                return ResourceManager.GetString("SaveCsvFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma Separated Values.
        /// </summary>
        public static string SaveCsvFileType {
            get {
                return ResourceManager.GetString("SaveCsvFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .graphml.
        /// </summary>
        public static string SaveGraphMLFileExtension {
            get {
                return ResourceManager.GetString("SaveGraphMLFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphML.
        /// </summary>
        public static string SaveGraphMLFileType {
            get {
                return ResourceManager.GetString("SaveGraphMLFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .zpp.
        /// </summary>
        public static string SaveProjectPlanFileExtension {
            get {
                return ResourceManager.GetString("SaveProjectPlanFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Plan.
        /// </summary>
        public static string SaveProjectPlanFileType {
            get {
                return ResourceManager.GetString("SaveProjectPlanFileType", resourceCulture);
            }
        }
    }
}
