//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Holidays {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Holidays() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Holidays", typeof(Holidays).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Holiday_Day {
            get {
                return ResourceManager.GetString("Holiday_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Holiday_Days {
            get {
                return ResourceManager.GetString("Holiday_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}st.
        /// </summary>
        public static string Holiday_FormatOrdinal1 {
            get {
                return ResourceManager.GetString("Holiday_FormatOrdinal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}nd.
        /// </summary>
        public static string Holiday_FormatOrdinal2 {
            get {
                return ResourceManager.GetString("Holiday_FormatOrdinal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}rd.
        /// </summary>
        public static string Holiday_FormatOrdinal3 {
            get {
                return ResourceManager.GetString("Holiday_FormatOrdinal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string Holiday_FormatOrdinalMinus1 {
            get {
                return ResourceManager.GetString("Holiday_FormatOrdinalMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}th.
        /// </summary>
        public static string Holiday_FormatOrdinalOther {
            get {
                return ResourceManager.GetString("Holiday_FormatOrdinalOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} {1}.
        /// </summary>
        public static string Holiday_FrequencyMultiple {
            get {
                return ResourceManager.GetString("Holiday_FrequencyMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0}.
        /// </summary>
        public static string Holiday_FrequencySingle {
            get {
                return ResourceManager.GetString("Holiday_FrequencySingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Holiday_Hour {
            get {
                return ResourceManager.GetString("Holiday_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Holiday_Hours {
            get {
                return ResourceManager.GetString("Holiday_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1}.
        /// </summary>
        public static string Holiday_JoinWithAnd {
            get {
                return ResourceManager.GetString("Holiday_JoinWithAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Holiday_Minute {
            get {
                return ResourceManager.GetString("Holiday_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Holiday_Minutes {
            get {
                return ResourceManager.GetString("Holiday_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string Holiday_Month {
            get {
                return ResourceManager.GetString("Holiday_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string Holiday_Months {
            get {
                return ResourceManager.GetString("Holiday_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string Holiday_Second {
            get {
                return ResourceManager.GetString("Holiday_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Holiday_Seconds {
            get {
                return ResourceManager.GetString("Holiday_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string Holiday_Week {
            get {
                return ResourceManager.GetString("Holiday_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Holiday_WeekdayFriday {
            get {
                return ResourceManager.GetString("Holiday_WeekdayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Holiday_WeekdayMonday {
            get {
                return ResourceManager.GetString("Holiday_WeekdayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Holiday_WeekdaySaturday {
            get {
                return ResourceManager.GetString("Holiday_WeekdaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Holiday_WeekdaySunday {
            get {
                return ResourceManager.GetString("Holiday_WeekdaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Holiday_WeekdayThursday {
            get {
                return ResourceManager.GetString("Holiday_WeekdayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Holiday_WeekdayTuesday {
            get {
                return ResourceManager.GetString("Holiday_WeekdayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Holiday_WeekdayWednesday {
            get {
                return ResourceManager.GetString("Holiday_WeekdayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string Holiday_Weeks {
            get {
                return ResourceManager.GetString("Holiday_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string Holiday_Year {
            get {
                return ResourceManager.GetString("Holiday_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string Holiday_Years {
            get {
                return ResourceManager.GetString("Holiday_Years", resourceCulture);
            }
        }
    }
}
