//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Holidays {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Holidays() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Holidays", typeof(Holidays).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string Holiday_After {
            get {
                return ResourceManager.GetString("Holiday_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on {0}.
        /// </summary>
        public static string Holiday_ByDay {
            get {
                return ResourceManager.GetString("Holiday_ByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in {0}.
        /// </summary>
        public static string Holiday_ByMonth {
            get {
                return ResourceManager.GetString("Holiday_ByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on the {0} {1}.
        /// </summary>
        public static string Holiday_ByMonthDay {
            get {
                return ResourceManager.GetString("Holiday_ByMonthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on the {0} {1}.
        /// </summary>
        public static string Holiday_BySetPosAndByDay {
            get {
                return ResourceManager.GetString("Holiday_BySetPosAndByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string Holiday_BySetPosFirst {
            get {
                return ResourceManager.GetString("Holiday_BySetPosFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        public static string Holiday_BySetPosFourth {
            get {
                return ResourceManager.GetString("Holiday_BySetPosFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Holiday_BySetPosLast {
            get {
                return ResourceManager.GetString("Holiday_BySetPosLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Holiday_BySetPosSecond {
            get {
                return ResourceManager.GetString("Holiday_BySetPosSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        public static string Holiday_BySetPosThird {
            get {
                return ResourceManager.GetString("Holiday_BySetPosThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for {0} occurrences.
        /// </summary>
        public static string Holiday_Count {
            get {
                return ResourceManager.GetString("Holiday_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Holiday_Day {
            get {
                return ResourceManager.GetString("Holiday_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Holiday_Days {
            get {
                return ResourceManager.GetString("Holiday_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Holiday_EditDay {
            get {
                return ResourceManager.GetString("Holiday_EditDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Holiday_EditOf {
            get {
                return ResourceManager.GetString("Holiday_EditOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string Holiday_EditThe {
            get {
                return ResourceManager.GetString("Holiday_EditThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends:.
        /// </summary>
        public static string Holiday_Ends {
            get {
                return ResourceManager.GetString("Holiday_Ends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}st.
        /// </summary>
        public static string Holiday_FormatOrdinal1 {
            get {
                return ResourceManager.GetString("Holiday_FormatOrdinal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}nd.
        /// </summary>
        public static string Holiday_FormatOrdinal2 {
            get {
                return ResourceManager.GetString("Holiday_FormatOrdinal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}rd.
        /// </summary>
        public static string Holiday_FormatOrdinal3 {
            get {
                return ResourceManager.GetString("Holiday_FormatOrdinal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string Holiday_FormatOrdinalMinus1 {
            get {
                return ResourceManager.GetString("Holiday_FormatOrdinalMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}th.
        /// </summary>
        public static string Holiday_FormatOrdinalOther {
            get {
                return ResourceManager.GetString("Holiday_FormatOrdinalOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Holiday_FrequencyDaily {
            get {
                return ResourceManager.GetString("Holiday_FrequencyDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Holiday_FrequencyMonthly {
            get {
                return ResourceManager.GetString("Holiday_FrequencyMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} {1}.
        /// </summary>
        public static string Holiday_FrequencyMultiple {
            get {
                return ResourceManager.GetString("Holiday_FrequencyMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Holiday_FrequencyNone {
            get {
                return ResourceManager.GetString("Holiday_FrequencyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0}.
        /// </summary>
        public static string Holiday_FrequencySingle {
            get {
                return ResourceManager.GetString("Holiday_FrequencySingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Holiday_FrequencyWeekly {
            get {
                return ResourceManager.GetString("Holiday_FrequencyWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string Holiday_FrequencyYearly {
            get {
                return ResourceManager.GetString("Holiday_FrequencyYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Holiday_Hour {
            get {
                return ResourceManager.GetString("Holiday_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Holiday_Hours {
            get {
                return ResourceManager.GetString("Holiday_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval:.
        /// </summary>
        public static string Holiday_Interval {
            get {
                return ResourceManager.GetString("Holiday_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1}.
        /// </summary>
        public static string Holiday_JoinWithAnd {
            get {
                return ResourceManager.GetString("Holiday_JoinWithAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Holiday_Minute {
            get {
                return ResourceManager.GetString("Holiday_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Holiday_Minutes {
            get {
                return ResourceManager.GetString("Holiday_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string Holiday_Month {
            get {
                return ResourceManager.GetString("Holiday_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Holiday_MonthApril {
            get {
                return ResourceManager.GetString("Holiday_MonthApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Holiday_MonthAugust {
            get {
                return ResourceManager.GetString("Holiday_MonthAugust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Holiday_MonthDecember {
            get {
                return ResourceManager.GetString("Holiday_MonthDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Holiday_MonthFebruary {
            get {
                return ResourceManager.GetString("Holiday_MonthFebruary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Holiday_MonthJanuary {
            get {
                return ResourceManager.GetString("Holiday_MonthJanuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Holiday_MonthJuly {
            get {
                return ResourceManager.GetString("Holiday_MonthJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Holiday_MonthJune {
            get {
                return ResourceManager.GetString("Holiday_MonthJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Holiday_MonthMarch {
            get {
                return ResourceManager.GetString("Holiday_MonthMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Holiday_MonthMay {
            get {
                return ResourceManager.GetString("Holiday_MonthMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Holiday_MonthNovember {
            get {
                return ResourceManager.GetString("Holiday_MonthNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Holiday_MonthOctober {
            get {
                return ResourceManager.GetString("Holiday_MonthOctober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string Holiday_Months {
            get {
                return ResourceManager.GetString("Holiday_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Holiday_MonthSeptember {
            get {
                return ResourceManager.GetString("Holiday_MonthSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Holiday_Never {
            get {
                return ResourceManager.GetString("Holiday_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no pattern.
        /// </summary>
        public static string Holiday_NoPattern {
            get {
                return ResourceManager.GetString("Holiday_NoPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurrences.
        /// </summary>
        public static string Holiday_Occurrences {
            get {
                return ResourceManager.GetString("Holiday_Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On date.
        /// </summary>
        public static string Holiday_OnDate {
            get {
                return ResourceManager.GetString("Holiday_OnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence Pattern.
        /// </summary>
        public static string Holiday_RecurrencePattern {
            get {
                return ResourceManager.GetString("Holiday_RecurrencePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence Rule (in English).
        /// </summary>
        public static string Holiday_RecurrencePatternAsPhrase {
            get {
                return ResourceManager.GetString("Holiday_RecurrencePatternAsPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence Rule.
        /// </summary>
        public static string Holiday_RecurrencePatternAsRule {
            get {
                return ResourceManager.GetString("Holiday_RecurrencePatternAsRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat on:.
        /// </summary>
        public static string Holiday_RepeatOn {
            get {
                return ResourceManager.GetString("Holiday_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string Holiday_Second {
            get {
                return ResourceManager.GetString("Holiday_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Holiday_Seconds {
            get {
                return ResourceManager.GetString("Holiday_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts:.
        /// </summary>
        public static string Holiday_Starts {
            get {
                return ResourceManager.GetString("Holiday_Starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  until {0}.
        /// </summary>
        public static string Holiday_Until {
            get {
                return ResourceManager.GetString("Holiday_Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string Holiday_Week {
            get {
                return ResourceManager.GetString("Holiday_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Holiday_WeekdayFriday {
            get {
                return ResourceManager.GetString("Holiday_WeekdayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string Holiday_WeekdayFridayShort {
            get {
                return ResourceManager.GetString("Holiday_WeekdayFridayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Holiday_WeekdayMonday {
            get {
                return ResourceManager.GetString("Holiday_WeekdayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string Holiday_WeekdayMondayShort {
            get {
                return ResourceManager.GetString("Holiday_WeekdayMondayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Holiday_WeekdaySaturday {
            get {
                return ResourceManager.GetString("Holiday_WeekdaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string Holiday_WeekdaySaturdayShort {
            get {
                return ResourceManager.GetString("Holiday_WeekdaySaturdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Holiday_WeekdaySunday {
            get {
                return ResourceManager.GetString("Holiday_WeekdaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Holiday_WeekdaySundayShort {
            get {
                return ResourceManager.GetString("Holiday_WeekdaySundayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Holiday_WeekdayThursday {
            get {
                return ResourceManager.GetString("Holiday_WeekdayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string Holiday_WeekdayThursdayShort {
            get {
                return ResourceManager.GetString("Holiday_WeekdayThursdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Holiday_WeekdayTuesday {
            get {
                return ResourceManager.GetString("Holiday_WeekdayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string Holiday_WeekdayTuesdayShort {
            get {
                return ResourceManager.GetString("Holiday_WeekdayTuesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Holiday_WeekdayWednesday {
            get {
                return ResourceManager.GetString("Holiday_WeekdayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string Holiday_WeekdayWednesdayShort {
            get {
                return ResourceManager.GetString("Holiday_WeekdayWednesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekdays.
        /// </summary>
        public static string Holiday_WeekdayWeekdays {
            get {
                return ResourceManager.GetString("Holiday_WeekdayWeekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekends.
        /// </summary>
        public static string Holiday_WeekdayWeekends {
            get {
                return ResourceManager.GetString("Holiday_WeekdayWeekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string Holiday_Weeks {
            get {
                return ResourceManager.GetString("Holiday_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with week starting {0}.
        /// </summary>
        public static string Holiday_WeekStart {
            get {
                return ResourceManager.GetString("Holiday_WeekStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string Holiday_Year {
            get {
                return ResourceManager.GetString("Holiday_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string Holiday_Years {
            get {
                return ResourceManager.GetString("Holiday_Years", resourceCulture);
            }
        }
    }
}
