//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Label_Activity {
            get {
                return ResourceManager.GetString("Label_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Effort:.
        /// </summary>
        public static string Label_ActivityEffort {
            get {
                return ResourceManager.GetString("Label_ActivityEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Name.
        /// </summary>
        public static string Label_ActivityName {
            get {
                return ResourceManager.GetString("Label_ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Risk:.
        /// </summary>
        public static string Label_ActivityRisk {
            get {
                return ResourceManager.GetString("Label_ActivityRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity (Std Dev) Risk:.
        /// </summary>
        public static string Label_ActivityRiskWithStdDevCorrection {
            get {
                return ResourceManager.GetString("Label_ActivityRiskWithStdDevCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Label_AddColumn {
            get {
                return ResourceManager.GetString("Label_AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Label_AddManagedActivity {
            get {
                return ResourceManager.GetString("Label_AddManagedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Label_AddManagedActivitySeverity {
            get {
                return ResourceManager.GetString("Label_AddManagedActivitySeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Label_AddManagedResource {
            get {
                return ResourceManager.GetString("Label_AddManagedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Label_AddManagedWorkStream {
            get {
                return ResourceManager.GetString("Label_AddManagedWorkStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string Label_AddMilestone {
            get {
                return ResourceManager.GetString("Label_AddMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated to Resources.
        /// </summary>
        public static string Label_AllocatedToResources {
            get {
                return ResourceManager.GetString("Label_AllocatedToResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation Style.
        /// </summary>
        public static string Label_AnnotationStyle {
            get {
                return ResourceManager.GetString("Label_AnnotationStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectplan.net.
        /// </summary>
        public static string Label_AppName {
            get {
                return ResourceManager.GetString("Label_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.9.0.
        /// </summary>
        public static string Label_AppVersion {
            get {
                return ResourceManager.GetString("Label_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R. M. Bennett-Lovsey.
        /// </summary>
        public static string Label_Author {
            get {
                return ResourceManager.GetString("Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available from:.
        /// </summary>
        public static string Label_AvailableFrom {
            get {
                return ResourceManager.GetString("Label_AvailableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_CancelSplashScreen {
            get {
                return ResourceManager.GetString("Label_CancelSplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set Minimum FS and Maximum LFT at the same time.
        /// </summary>
        public static string Label_CannotSetMinimumFreeSlackAndMaximumLatestFinishTimeAtSameTime {
            get {
                return ResourceManager.GetString("Label_CannotSetMinimumFreeSlackAndMaximumLatestFinishTimeAtSameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectplan.net cli.
        /// </summary>
        public static string Label_CliAppName {
            get {
                return ResourceManager.GetString("Label_CliAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Label_ColorFormat {
            get {
                return ResourceManager.GetString("Label_ColorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2024.
        /// </summary>
        public static string Label_Copyright {
            get {
                return ResourceManager.GetString("Label_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticality Risk:.
        /// </summary>
        public static string Label_CriticalityRisk {
            get {
                return ResourceManager.GetString("Label_CriticalityRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticality Weight.
        /// </summary>
        public static string Label_CriticalityWeight {
            get {
                return ResourceManager.GetString("Label_CriticalityWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic Complexity:.
        /// </summary>
        public static string Label_CyclomaticComplexity {
            get {
                return ResourceManager.GetString("Label_CyclomaticComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Label_Day {
            get {
                return ResourceManager.GetString("Label_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days shown:.
        /// </summary>
        public static string Label_DaysShown {
            get {
                return ResourceManager.GetString("Label_DaysShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Label_Default {
            get {
                return ResourceManager.GetString("Label_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Unit Cost.
        /// </summary>
        public static string Label_DefaultUnitCost {
            get {
                return ResourceManager.GetString("Label_DefaultUnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Label_DefaultWorkStream {
            get {
                return ResourceManager.GetString("Label_DefaultWorkStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_DeleteColumn {
            get {
                return ResourceManager.GetString("Label_DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_DeleteManagedActivity {
            get {
                return ResourceManager.GetString("Label_DeleteManagedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_DeleteManagedActivitySeverities {
            get {
                return ResourceManager.GetString("Label_DeleteManagedActivitySeverities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_DeleteManagedResources {
            get {
                return ResourceManager.GetString("Label_DeleteManagedResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_DeleteManagedWorkStreams {
            get {
                return ResourceManager.GetString("Label_DeleteManagedWorkStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Label_Dependencies {
            get {
                return ResourceManager.GetString("Label_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Cost:.
        /// </summary>
        public static string Label_DirectCost {
            get {
                return ResourceManager.GetString("Label_DirectCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Effort:.
        /// </summary>
        public static string Label_DirectEffort {
            get {
                return ResourceManager.GetString("Label_DirectEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Resources.
        /// </summary>
        public static string Label_DisableResources {
            get {
                return ResourceManager.GetString("Label_DisableResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string Label_DisplayOrder {
            get {
                return ResourceManager.GetString("Label_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Label_Duration {
            get {
                return ResourceManager.GetString("Label_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (months):.
        /// </summary>
        public static string Label_DurationManMonths {
            get {
                return ResourceManager.GetString("Label_DurationManMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFT.
        /// </summary>
        public static string Label_EarliestFinishTime {
            get {
                return ResourceManager.GetString("Label_EarliestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EST.
        /// </summary>
        public static string Label_EarliestStartTime {
            get {
                return ResourceManager.GetString("Label_EarliestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency:.
        /// </summary>
        public static string Label_Efficiency {
            get {
                return ResourceManager.GetString("Label_Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effort.
        /// </summary>
        public static string Label_Effort {
            get {
                return ResourceManager.GetString("Label_Effort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effort Projection.
        /// </summary>
        public static string Label_EffortProjection {
            get {
                return ResourceManager.GetString("Label_EffortProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Label_End {
            get {
                return ResourceManager.GetString("Label_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci Risk:.
        /// </summary>
        public static string Label_FibonacciRisk {
            get {
                return ResourceManager.GetString("Label_FibonacciRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci Weight.
        /// </summary>
        public static string Label_FibonacciWeight {
            get {
                return ResourceManager.GetString("Label_FibonacciWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Label_Find {
            get {
                return ResourceManager.GetString("Label_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FS.
        /// </summary>
        public static string Label_FreeSlack {
            get {
                return ResourceManager.GetString("Label_FreeSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Activities.
        /// </summary>
        public static string Label_GanttAxisTitle {
            get {
                return ResourceManager.GetString("Label_GanttAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Activities.
        /// </summary>
        public static string Label_GanttChartSeries {
            get {
                return ResourceManager.GetString("Label_GanttChartSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric (Act.) Risk:.
        /// </summary>
        public static string Label_GeometricActivityRisk {
            get {
                return ResourceManager.GetString("Label_GeometricActivityRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric (Crit.) Risk:.
        /// </summary>
        public static string Label_GeometricCriticalityRisk {
            get {
                return ResourceManager.GetString("Label_GeometricCriticalityRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric (Fib.) Risk:.
        /// </summary>
        public static string Label_GeometricFibonacciRisk {
            get {
                return ResourceManager.GetString("Label_GeometricFibonacciRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by.
        /// </summary>
        public static string Label_GroupByMode {
            get {
                return ResourceManager.GetString("Label_GroupByMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Cost.
        /// </summary>
        public static string Label_HasNoCost {
            get {
                return ResourceManager.GetString("Label_HasNoCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Label_Id {
            get {
                return ResourceManager.GetString("Label_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Cost:.
        /// </summary>
        public static string Label_IndirectCost {
            get {
                return ResourceManager.GetString("Label_IndirectCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Effort:.
        /// </summary>
        public static string Label_IndirectEffort {
            get {
                return ResourceManager.GetString("Label_IndirectEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter-activity Allocation.
        /// </summary>
        public static string Label_InterActivityAllocationType {
            get {
                return ResourceManager.GetString("Label_InterActivityAllocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter-activity Phases.
        /// </summary>
        public static string Label_InterActivityPhases {
            get {
                return ResourceManager.GetString("Label_InterActivityPhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS.
        /// </summary>
        public static string Label_InterferingSlack {
            get {
                return ResourceManager.GetString("Label_InterferingSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        public static string Label_InvalidFormat {
            get {
                return ResourceManager.GetString("Label_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string Label_IsCritical {
            get {
                return ResourceManager.GetString("Label_IsCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy.
        /// </summary>
        public static string Label_IsDummy {
            get {
                return ResourceManager.GetString("Label_IsDummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit Target.
        /// </summary>
        public static string Label_IsExplicitTarget {
            get {
                return ResourceManager.GetString("Label_IsExplicitTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Label_IsInactive {
            get {
                return ResourceManager.GetString("Label_IsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        public static string Label_IsPhase {
            get {
                return ResourceManager.GetString("Label_IsPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Groups.
        /// </summary>
        public static string Label_LabelGroups {
            get {
                return ResourceManager.GetString("Label_LabelGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LFT.
        /// </summary>
        public static string Label_LatestFinishTime {
            get {
                return ResourceManager.GetString("Label_LatestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LST.
        /// </summary>
        public static string Label_LatestStartTime {
            get {
                return ResourceManager.GetString("Label_LatestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Label_Max {
            get {
                return ResourceManager.GetString("Label_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum LFT.
        /// </summary>
        public static string Label_MaximumLatestFinishTime {
            get {
                return ResourceManager.GetString("Label_MaximumLatestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum EST.
        /// </summary>
        public static string Label_MinimumEarliestStartTime {
            get {
                return ResourceManager.GetString("Label_MinimumEarliestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum EST to Maximum LFT must be &gt;= Duration.
        /// </summary>
        public static string Label_MinimumEarliestStartTimeToMaximumLatestFinishTimeMustBeGreaterThanOrEqualToDuration {
            get {
                return ResourceManager.GetString("Label_MinimumEarliestStartTimeToMaximumLatestFinishTimeMustBeGreaterThanOrEqualTo" +
                        "Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum FS.
        /// </summary>
        public static string Label_MinimumFreeSlack {
            get {
                return ResourceManager.GetString("Label_MinimumFreeSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Label_No {
            get {
                return ResourceManager.GetString("Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Label_Notes {
            get {
                return ResourceManager.GetString("Label_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Cost:.
        /// </summary>
        public static string Label_OtherCost {
            get {
                return ResourceManager.GetString("Label_OtherCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Effort:.
        /// </summary>
        public static string Label_OtherEffort {
            get {
                return ResourceManager.GetString("Label_OtherEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage (%).
        /// </summary>
        public static string Label_PercentageAxisTitle {
            get {
                return ResourceManager.GetString("Label_PercentageAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Label_PercentageCompleted {
            get {
                return ResourceManager.GetString("Label_PercentageCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Label_Plan {
            get {
                return ResourceManager.GetString("Label_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Projection.
        /// </summary>
        public static string Label_PlanProjection {
            get {
                return ResourceManager.GetString("Label_PlanProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string Label_PleaseWait {
            get {
                return ResourceManager.GetString("Label_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Label_Progress {
            get {
                return ResourceManager.GetString("Label_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Projection.
        /// </summary>
        public static string Label_ProgressProjection {
            get {
                return ResourceManager.GetString("Label_ProgressProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Completion.
        /// </summary>
        public static string Label_ProjectCompletion {
            get {
                return ResourceManager.GetString("Label_ProjectCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Finish:.
        /// </summary>
        public static string Label_ProjectFinish {
            get {
                return ResourceManager.GetString("Label_ProjectFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Start:.
        /// </summary>
        public static string Label_ProjectStart {
            get {
                return ResourceManager.GetString("Label_ProjectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string Label_Resource {
            get {
                return ResourceManager.GetString("Label_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Dependencies.
        /// </summary>
        public static string Label_ResourceDependencies {
            get {
                return ResourceManager.GetString("Label_ResourceDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Name.
        /// </summary>
        public static string Label_ResourceName {
            get {
                return ResourceManager.GetString("Label_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Label_ResourcesAxisTitle {
            get {
                return ResourceManager.GetString("Label_ResourcesAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self dependency.
        /// </summary>
        public static string Label_SelfDependency {
            get {
                return ResourceManager.GetString("Label_SelfDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Project Finish.
        /// </summary>
        public static string Label_ShowProjectFinish {
            get {
                return ResourceManager.GetString("Label_ShowProjectFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tracking.
        /// </summary>
        public static string Label_ShowTracking {
            get {
                return ResourceManager.GetString("Label_ShowTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slack Limit.
        /// </summary>
        public static string Label_SlackLimit {
            get {
                return ResourceManager.GetString("Label_SlackLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Label_Start {
            get {
                return ResourceManager.GetString("Label_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start day:.
        /// </summary>
        public static string Label_StartDay {
            get {
                return ResourceManager.GetString("Label_StartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Operator.
        /// </summary>
        public static string Label_TargetResourceOperator {
            get {
                return ResourceManager.GetString("Label_TargetResourceOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Resources.
        /// </summary>
        public static string Label_TargetResources {
            get {
                return ResourceManager.GetString("Label_TargetResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Work Streams.
        /// </summary>
        public static string Label_TargetWorkStreams {
            get {
                return ResourceManager.GetString("Label_TargetWorkStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Label_TimeAxisTitle {
            get {
                return ResourceManager.GetString("Label_TimeAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string Label_To {
            get {
                return ResourceManager.GetString("Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost:.
        /// </summary>
        public static string Label_TotalCost {
            get {
                return ResourceManager.GetString("Label_TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Effort:.
        /// </summary>
        public static string Label_TotalEffort {
            get {
                return ResourceManager.GetString("Label_TotalEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS.
        /// </summary>
        public static string Label_TotalSlack {
            get {
                return ResourceManager.GetString("Label_TotalSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string Label_UnitCost {
            get {
                return ResourceManager.GetString("Label_UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Projections.
        /// </summary>
        public static string Label_ViewProjections {
            get {
                return ResourceManager.GetString("Label_ViewProjections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Stream Name.
        /// </summary>
        public static string Label_WorkStreamName {
            get {
                return ResourceManager.GetString("Label_WorkStreamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Label_Yes {
            get {
                return ResourceManager.GetString("Label_Yes", resourceCulture);
            }
        }
    }
}
