//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Menus", typeof(Menus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Compile.
        /// </summary>
        public static string Menu_AutoCompile {
            get {
                return ResourceManager.GetString("Menu_AutoCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Menu_Close {
            get {
                return ResourceManager.GetString("Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string Menu_Compile {
            get {
                return ResourceManager.GetString("Menu_Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Settings.
        /// </summary>
        public static string Menu_DefaultSettings {
            get {
                return ResourceManager.GetString("Menu_DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Menu_Documentation {
            get {
                return ResourceManager.GetString("Menu_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Menu_Donate {
            get {
                return ResourceManager.GetString("Menu_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export....
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Billing.
        /// </summary>
        public static string Menu_HideBilling {
            get {
                return ResourceManager.GetString("Menu_HideBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Cost.
        /// </summary>
        public static string Menu_HideCost {
            get {
                return ResourceManager.GetString("Menu_HideCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import....
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Calendar.
        /// </summary>
        public static string Menu_NonWorkingDaysCustomCalendar {
            get {
                return ResourceManager.GetString("Menu_NonWorkingDaysCustomCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Menu_NonWorkingDaysNone {
            get {
                return ResourceManager.GetString("Menu_NonWorkingDaysNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Working Days.
        /// </summary>
        public static string Menu_NonWorkingDaysSettings {
            get {
                return ResourceManager.GetString("Menu_NonWorkingDaysSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekends.
        /// </summary>
        public static string Menu_NonWorkingDaysWeekends {
            get {
                return ResourceManager.GetString("Menu_NonWorkingDaysWeekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string Menu_ReportIssue {
            get {
                return ResourceManager.GetString("Menu_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Menu_Reset {
            get {
                return ResourceManager.GetString("Menu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Layout.
        /// </summary>
        public static string Menu_ResetDockLayout {
            get {
                return ResourceManager.GetString("Menu_ResetDockLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _Layout.
        /// </summary>
        public static string Menu_SaveLayout {
            get {
                return ResourceManager.GetString("Menu_SaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Dates.
        /// </summary>
        public static string Menu_ShowDates {
            get {
                return ResourceManager.GetString("Menu_ShowDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Menu_Sort {
            get {
                return ResourceManager.GetString("Menu_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Menu_SortDirectionAscending {
            get {
                return ResourceManager.GetString("Menu_SortDirectionAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Menu_SortDirectionDescending {
            get {
                return ResourceManager.GetString("Menu_SortDirectionDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string Menu_SortModeCreatedOn {
            get {
                return ResourceManager.GetString("Menu_SortModeCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        public static string Menu_SortModeModifiedOn {
            get {
                return ResourceManager.GetString("Menu_SortModeModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Menu_SortModeName {
            get {
                return ResourceManager.GetString("Menu_SortModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Menu_Themes {
            get {
                return ResourceManager.GetString("Menu_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transitive Reduction.
        /// </summary>
        public static string Menu_TransitiveReduction {
            get {
                return ResourceManager.GetString("Menu_TransitiveReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Classic Dates.
        /// </summary>
        public static string Menu_UseClassicDates {
            get {
                return ResourceManager.GetString("Menu_UseClassicDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License.
        /// </summary>
        public static string Menu_ViewLicense {
            get {
                return ResourceManager.GetString("Menu_ViewLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Menu_AddManagedActivity {
            get {
                return ResourceManager.GetString("Menu_AddManagedActivity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Menu_AddManagedActivitySeverity {
            get {
                return ResourceManager.GetString("Menu_AddManagedActivitySeverity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Menu_AddManagedHoliday {
            get {
                return ResourceManager.GetString("Menu_AddManagedHoliday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Menu_AddManagedResource {
            get {
                return ResourceManager.GetString("Menu_AddManagedResource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Menu_AddManagedWorkStream {
            get {
                return ResourceManager.GetString("Menu_AddManagedWorkStream", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string Menu_AddMilestone {
            get {
                return ResourceManager.GetString("Menu_AddMilestone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Tag.
        /// </summary>
        public static string Menu_AddTag {
            get {
                return ResourceManager.GetString("Menu_AddTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        public static string Menu_AllocationMode {
            get {
                return ResourceManager.GetString("Menu_AllocationMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Annotation Style.
        /// </summary>
        public static string Menu_AnnotationStyle {
            get {
                return ResourceManager.GetString("Menu_AnnotationStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Menu_CopyNode {
            get {
                return ResourceManager.GetString("Menu_CopyNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Curve Fitting.
        /// </summary>
        public static string Menu_CurveFittingType {
            get {
                return ResourceManager.GetString("Menu_CurveFittingType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Menu_CutNode {
            get {
                return ResourceManager.GetString("Menu_CutNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_DeleteManagedActivities {
            get {
                return ResourceManager.GetString("Menu_DeleteManagedActivities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_DeleteManagedActivitySeverities {
            get {
                return ResourceManager.GetString("Menu_DeleteManagedActivitySeverities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_DeleteManagedHolidays {
            get {
                return ResourceManager.GetString("Menu_DeleteManagedHolidays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_DeleteManagedResources {
            get {
                return ResourceManager.GetString("Menu_DeleteManagedResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_DeleteManagedWorkStreams {
            get {
                return ResourceManager.GetString("Menu_DeleteManagedWorkStreams", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_DeleteNode {
            get {
                return ResourceManager.GetString("Menu_DeleteNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Tag.
        /// </summary>
        public static string Menu_DeleteTag {
            get {
                return ResourceManager.GetString("Menu_DeleteTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disable Resources.
        /// </summary>
        public static string Menu_DisableResources {
            get {
                return ResourceManager.GetString("Menu_DisableResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display style.
        /// </summary>
        public static string Menu_DisplayStyle {
            get {
                return ResourceManager.GetString("Menu_DisplayStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Menu_DuplicateManagedActivity {
            get {
                return ResourceManager.GetString("Menu_DuplicateManagedActivity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Menu_DuplicateManagedActivitySeverity {
            get {
                return ResourceManager.GetString("Menu_DuplicateManagedActivitySeverity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Menu_DuplicateManagedHoliday {
            get {
                return ResourceManager.GetString("Menu_DuplicateManagedHoliday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Menu_DuplicateManagedResource {
            get {
                return ResourceManager.GetString("Menu_DuplicateManagedResource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Menu_DuplicateManagedWorkStream {
            get {
                return ResourceManager.GetString("Menu_DuplicateManagedWorkStream", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Menu_DuplicateNode {
            get {
                return ResourceManager.GetString("Menu_DuplicateNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Menu_EditManagedActivities {
            get {
                return ResourceManager.GetString("Menu_EditManagedActivities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Menu_EditManagedHoliday {
            get {
                return ResourceManager.GetString("Menu_EditManagedHoliday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Menu_EditManagedResources {
            get {
                return ResourceManager.GetString("Menu_EditManagedResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Menu_EditManagedWorkStreams {
            get {
                return ResourceManager.GetString("Menu_EditManagedWorkStreams", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group by.
        /// </summary>
        public static string Menu_GroupByMode {
            get {
                return ResourceManager.GetString("Menu_GroupByMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Menu_InsertManagedActivity {
            get {
                return ResourceManager.GetString("Menu_InsertManagedActivity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Scenario.
        /// </summary>
        public static string Menu_NewScenario {
            get {
                return ResourceManager.GetString("Menu_NewScenario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string Menu_NewScenarioFolder {
            get {
                return ResourceManager.GetString("Menu_NewScenarioFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Menu_PasteNode {
            get {
                return ResourceManager.GetString("Menu_PasteNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Menu_RenameNode {
            get {
                return ResourceManager.GetString("Menu_RenameNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Renumber.
        /// </summary>
        public static string Menu_RenumberActivities {
            get {
                return ResourceManager.GetString("Menu_RenumberActivities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Renumber.
        /// </summary>
        public static string Menu_RenumberResources {
            get {
                return ResourceManager.GetString("Menu_RenumberResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Renumber.
        /// </summary>
        public static string Menu_RenumberWorkStreams {
            get {
                return ResourceManager.GetString("Menu_RenumberWorkStreams", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Menu_ScheduleMode {
            get {
                return ResourceManager.GetString("Menu_ScheduleMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Menu_SelectManagedScenario {
            get {
                return ResourceManager.GetString("Menu_SelectManagedScenario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Group Labels.
        /// </summary>
        public static string Menu_ShowGroupLabels {
            get {
                return ResourceManager.GetString("Menu_ShowGroupLabels", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Milestones.
        /// </summary>
        public static string Menu_ShowMilestones {
            get {
                return ResourceManager.GetString("Menu_ShowMilestones", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Names.
        /// </summary>
        public static string Menu_ShowNames {
            get {
                return ResourceManager.GetString("Menu_ShowNames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Non-Working Days.
        /// </summary>
        public static string Menu_ShowNonWorkingDays {
            get {
                return ResourceManager.GetString("Menu_ShowNonWorkingDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Project Finish.
        /// </summary>
        public static string Menu_ShowProjectFinish {
            get {
                return ResourceManager.GetString("Menu_ShowProjectFinish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Projections.
        /// </summary>
        public static string Menu_ShowProjections {
            get {
                return ResourceManager.GetString("Menu_ShowProjections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Slack.
        /// </summary>
        public static string Menu_ShowSlack {
            get {
                return ResourceManager.GetString("Menu_ShowSlack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Today.
        /// </summary>
        public static string Menu_ShowToday {
            get {
                return ResourceManager.GetString("Menu_ShowToday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Tracking.
        /// </summary>
        public static string Menu_ShowTracking {
            get {
                return ResourceManager.GetString("Menu_ShowTracking", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to X Axis Metric.
        /// </summary>
        public static string Menu_TrackedMetricXAxis {
            get {
                return ResourceManager.GetString("Menu_TrackedMetricXAxis", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Y Axis Metric.
        /// </summary>
        public static string Menu_TrackedMetricYAxis {
            get {
                return ResourceManager.GetString("Menu_TrackedMetricYAxis", resourceCulture);
            }
        }
    }
}
