//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag to node.
        /// </summary>
        public static string Message_AddTag {
            get {
                return ResourceManager.GetString("Message_AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not an option, nor the value of one: {1} lists the options..
        /// </summary>
        public static string Message_ArgumentNotOptionOrValue {
            get {
                return ResourceManager.GetString("Message_ArgumentNotOptionOrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph Data contain more than one End node.
        /// </summary>
        public static string Message_ArrowGraphDataContainMultipleEndNodes {
            get {
                return ResourceManager.GetString("Message_ArrowGraphDataContainMultipleEndNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph Data contain more than one Start node.
        /// </summary>
        public static string Message_ArrowGraphDataContainMultipleStartNodes {
            get {
                return ResourceManager.GetString("Message_ArrowGraphDataContainMultipleStartNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} cannot both be set.
        /// </summary>
        public static string Message_CannotBothBeSet {
            get {
                return ResourceManager.GetString("Message_CannotBothBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build arrow graph.
        /// </summary>
        public static string Message_CannotBuildArrowGraph {
            get {
                return ResourceManager.GetString("Message_CannotBuildArrowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a project scenario file from a folder node:.
        /// </summary>
        public static string Message_CannotGetProjectScenarioFileFromFolderNode {
            get {
                return ResourceManager.GetString("Message_CannotGetProjectScenarioFileFromFolderNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a project scenario file when project scenario is null:.
        /// </summary>
        public static string Message_CannotGetProjectScenarioFileWhenProjectScenarioIsNull {
            get {
                return ResourceManager.GetString("Message_CannotGetProjectScenarioFileWhenProjectScenarioIsNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cut nodes cannot be pasted into themselves or their own subfolders.
        /// </summary>
        public static string Message_CannotPasteCutNodesIntoOwnSubtree {
            get {
                return ResourceManager.GetString("Message_CannotPasteCutNodesIntoOwnSubtree", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot set a project scenario on a folder node:.
        /// </summary>
        public static string Message_CannotSetProjectScenarioOnFolderNode {
            get {
                return ResourceManager.GetString("Message_CannotSetProjectScenarioOnFolderNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot track a project scenario file from a folder node:.
        /// </summary>
        public static string Message_CannotTrackProjectScenarioFileFromFolderNode {
            get {
                return ResourceManager.GetString("Message_CannotTrackProjectScenarioFileFromFolderNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of recently opened files will be cleared. This action is irreversible! Do you wish to continue?.
        /// </summary>
        public static string Message_ClearRecentlyOpened {
            get {
                return ResourceManager.GetString("Message_ClearRecentlyOpened", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copying the chart image to the clipboard failed. Use Save As instead..
        /// </summary>
        public static string Message_ClipboardCopyFailed {
            get {
                return ResourceManager.GetString("Message_ClipboardCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnType must be derived from DataGridColumn.
        /// </summary>
        public static string Message_ColumnTypeMustBeDerivedFromDataGridColumn {
            get {
                return ResourceManager.GetString("Message_ColumnTypeMustBeDerivedFromDataGridColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation errors.
        /// </summary>
        public static string Message_CompilationErrors {
            get {
                return ResourceManager.GetString("Message_CompilationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compilation did not complete within the time limit of {0} ms and was cancelled. Raise the compilation timeout to allow longer..
        /// </summary>
        public static string Message_CompilationTimedOut {
            get {
                return ResourceManager.GetString("Message_CompilationTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted from previous version.
        /// </summary>
        public static string Message_ConvertedFromPreviousVersion {
            get {
                return ResourceManager.GetString("Message_ConvertedFromPreviousVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticality Weight must be equal or greater than 0.
        /// </summary>
        public static string Message_CriticalityWeightMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_CriticalityWeightMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a culture this machine knows..
        /// </summary>
        public static string Message_CultureNotKnown {
            get {
                return ResourceManager.GetString("Message_CultureNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Day.
        /// </summary>
        public static string Message_DefaultChristmasDayName {
            get {
                return ResourceManager.GetString("Message_DefaultChristmasDayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas holiday.
        /// </summary>
        public static string Message_DefaultChristmasDayNotes {
            get {
                return ResourceManager.GetString("Message_DefaultChristmasDayNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year&apos;s Day.
        /// </summary>
        public static string Message_DefaultNewYearsDayName {
            get {
                return ResourceManager.GetString("Message_DefaultNewYearsDayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year&apos;s holiday.
        /// </summary>
        public static string Message_DefaultNewYearsDayNotes {
            get {
                return ResourceManager.GetString("Message_DefaultNewYearsDayNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekends.
        /// </summary>
        public static string Message_DefaultWeekendsName {
            get {
                return ResourceManager.GetString("Message_DefaultWeekendsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekends off.
        /// </summary>
        public static string Message_DefaultWeekendsNotes {
            get {
                return ResourceManager.GetString("Message_DefaultWeekendsNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tag from node.
        /// </summary>
        public static string Message_DeleteTag {
            get {
                return ResourceManager.GetString("Message_DeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} does not exist.
        /// </summary>
        public static string Message_DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("Message_DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete the {0} selected node(s)?.
        /// </summary>
        public static string Message_DoYouWishToDeleteTheseScenarios {
            get {
                return ResourceManager.GetString("Message_DoYouWishToDeleteTheseScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate RRULE part: &apos;{0}&apos;.
        /// </summary>
        public static string Message_DuplicateRRulePart {
            get {
                return ResourceManager.GetString("Message_DuplicateRRulePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the properties to edit.
        /// </summary>
        public static string Message_EditActivities {
            get {
                return ResourceManager.GetString("Message_EditActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure custom calendar.
        /// </summary>
        public static string Message_EditCustomCalendar {
            get {
                return ResourceManager.GetString("Message_EditCustomCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the properties to edit.
        /// </summary>
        public static string Message_EditResources {
            get {
                return ResourceManager.GetString("Message_EditResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the properties to edit.
        /// </summary>
        public static string Message_EditWorkStreams {
            get {
                return ResourceManager.GetString("Message_EditWorkStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty filename.
        /// </summary>
        public static string Message_EmptyFilename {
            get {
                return ResourceManager.GetString("Message_EmptyFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci Weight must be equal or greater than 0.
        /// </summary>
        public static string Message_FibonacciWeightMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_FibonacciWeightMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty..
        /// </summary>
        public static string Message_FileIsEmpty {
            get {
                return ResourceManager.GetString("Message_FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Billing must be equal to or greater than 0 .
        /// </summary>
        public static string Message_FixedBillingMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("Message_FixedBillingMustBeZeroOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Cost must be equal to or greater than 0.
        /// </summary>
        public static string Message_FixedCostMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("Message_FixedCostMustBeZeroOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Frequency value: &apos;{0}&apos;.
        /// </summary>
        public static string Message_InvalidFrequencyValue {
            get {
                return ResourceManager.GetString("Message_InvalidFrequencyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} value: &apos;{1}&apos;.
        /// </summary>
        public static string Message_InvalidInputValue {
            get {
                return ResourceManager.GetString("Message_InvalidInputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RRULE part: &apos;{0}&apos;.
        /// </summary>
        public static string Message_InvalidRRulePart {
            get {
                return ResourceManager.GetString("Message_InvalidRRulePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by head Nodes do not match when building Arrow Graph.
        /// </summary>
        public static string Message_MismatchedEdgeIdsForHeadNodesInArrowGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedEdgeIdsForHeadNodesInArrowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by head Nodes do not match when building Vertex Graph.
        /// </summary>
        public static string Message_MismatchedEdgeIdsForHeadNodesInVertexGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedEdgeIdsForHeadNodesInVertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by tail Nodes do not match when building Arrow Graph.
        /// </summary>
        public static string Message_MismatchedEdgeIdsForTailNodesInArrowGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedEdgeIdsForTailNodesInArrowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by tail Nodes do not match when building Vertex Graph.
        /// </summary>
        public static string Message_MismatchedEdgeIdsForTailNodesInVertexGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedEdgeIdsForTailNodesInVertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Node IDs and Nodes associated with Edges do not match when building Arrow Graph.
        /// </summary>
        public static string Message_MismatchedNodeIdsAssociatedWithEdgesInArrowGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedNodeIdsAssociatedWithEdgesInArrowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Node IDs and Nodes associated with Edges do not match when building Vertex Graph.
        /// </summary>
        public static string Message_MismatchedNodeIdsAssociatedWithEdgesInVertexGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedNodeIdsAssociatedWithEdgesInVertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than zero ({1}).
        /// </summary>
        public static string Message_MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_MustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be either -1 or greater than zero.
        /// </summary>
        public static string Message_MustBeMinusOneOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_MustBeMinusOneOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        public static string Message_NameAlreadyExists {
            get {
                return ResourceManager.GetString("Message_NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        public static string Message_NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("Message_NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Trackers must be equal or greater than 0.
        /// </summary>
        public static string Message_NewTrackersMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_NewTrackersMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scenario matches &apos;{0}&apos; - use {1} to see what the project contains.
        /// </summary>
        public static string Message_NoScenarioMatches {
            get {
                return ResourceManager.GetString("Message_NoScenarioMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scenario matches &apos;{0}&apos;.
        /// </summary>
        public static string Message_NoScenarioMatchesSelector {
            get {
                return ResourceManager.GetString("Message_NoScenarioMatchesSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Window icon available.
        /// </summary>
        public static string Message_NoWindowIconAvailable {
            get {
                return ResourceManager.GetString("Message_NoWindowIconAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of Trackers across all Activities is not identical.
        /// </summary>
        public static string Message_NumberOfTrackersAcrossAllActivitiesNotIdentical {
            get {
                return ResourceManager.GetString("Message_NumberOfTrackersAcrossAllActivitiesNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be negative (use 0 for no limit)..
        /// </summary>
        public static string Message_OptionCannotBeNegative {
            get {
                return ResourceManager.GetString("Message_OptionCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be given once..
        /// </summary>
        public static string Message_OptionGivenMoreThanOnce {
            get {
                return ResourceManager.GetString("Message_OptionGivenMoreThanOnce", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} must be a date and time with its offset from UTC, such as 2026-09-27T12:00:00+01:00 or 2026-09-27T11:00:00Z..
        /// </summary>
        public static string Message_OptionMustBeADateTimeWithOffset {
            get {
                return ResourceManager.GetString("Message_OptionMustBeADateTimeWithOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs a value..
        /// </summary>
        public static string Message_OptionNeedsValue {
            get {
                return ResourceManager.GetString("Message_OptionNeedsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is only valid when zpp runs on a server: use {1}, or set {2}..
        /// </summary>
        public static string Message_OptionOnlyValidWithServer {
            get {
                return ResourceManager.GetString("Message_OptionOnlyValidWithServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is required when {1} is specified..
        /// </summary>
        public static string Message_OptionRequiredWithOption {
            get {
                return ResourceManager.GetString("Message_OptionRequiredWithOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} are only valid with {2}..
        /// </summary>
        public static string Message_OptionsOnlyValidWithOption {
            get {
                return ResourceManager.GetString("Message_OptionsOnlyValidWithOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} takes at most {1} values..
        /// </summary>
        public static string Message_OptionTakesAtMostValues {
            get {
                return ResourceManager.GetString("Message_OptionTakesAtMostValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} takes no value..
        /// </summary>
        public static string Message_OptionTakesNoValue {
            get {
                return ResourceManager.GetString("Message_OptionTakesNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project has unsaved changes that will be lost. Do you wish to continue without saving?.
        /// </summary>
        public static string Message_ProjectUnsavedChanges {
            get {
                return ResourceManager.GetString("Message_ProjectUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RRule must contain &apos;{0}&apos;.
        /// </summary>
        public static string Message_RRuleMustContain {
            get {
                return ResourceManager.GetString("Message_RRuleMustContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario &apos;{0}&apos; has no scenario data in the project file.
        /// </summary>
        public static string Message_ScenarioHasNoScenarioData {
            get {
                return ResourceManager.GetString("Message_ScenarioHasNoScenarioData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scenario has unsaved changes that will be lost. Do you wish to continue without saving?.
        /// </summary>
        public static string Message_ScenarioUnsavedChanges {
            get {
                return ResourceManager.GetString("Message_ScenarioUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request needs the server&apos;s API key, as Authorization: Bearer &lt;key&gt;..
        /// </summary>
        public static string Message_ServeApiKeyRequired {
            get {
                return ResourceManager.GetString("Message_ServeApiKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is running all the jobs it can, with as many waiting as it allows. Try again shortly..
        /// </summary>
        public static string Message_ServeBusy {
            get {
                return ResourceManager.GetString("Message_ServeBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zpp serve imports .xlsx files only: import {0} with zpp itself..
        /// </summary>
        public static string Message_ServeCannotImport {
            get {
                return ResourceManager.GetString("Message_ServeCannotImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is only valid with an https address to listen on..
        /// </summary>
        public static string Message_ServeCertificateNeedsHttps {
            get {
                return ResourceManager.GetString("Message_ServeCertificateNeedsHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be from 1 to {1} pixels wide and from 1 to {2} pixels high..
        /// </summary>
        public static string Message_ServeChartSizeOutOfRange {
            get {
                return ResourceManager.GetString("Message_ServeChartSizeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;compileTimeout&apos; must be from 1 to {0} milliseconds..
        /// </summary>
        public static string Message_ServeCompileTimeoutOutOfRange {
            get {
                return ResourceManager.GetString("Message_ServeCompileTimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs a certificate: use {1}..
        /// </summary>
        public static string Message_ServeHttpsNeedsCertificate {
            get {
                return ResourceManager.GetString("Message_ServeHttpsNeedsCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job ran for longer than the server&apos;s limit of {0} seconds, and was stopped..
        /// </summary>
        public static string Message_ServeJobTimedOut {
            get {
                return ResourceManager.GetString("Message_ServeJobTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) must be at least {2}..
        /// </summary>
        public static string Message_ServeLimitTooLow {
            get {
                return ResourceManager.GetString("Message_ServeLimitTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not an address zpp serve can listen on: give http or https, then localhost, an IP address or *, then a port - such as http://localhost:9770..
        /// </summary>
        public static string Message_ServeListenAddressNotValid {
            get {
                return ResourceManager.GetString("Message_ServeListenAddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other machines can reach {0}, so zpp serve needs an API key to listen there: set {1}, or use {2}..
        /// </summary>
        public static string Message_ServeNeedsApiKey {
            get {
                return ResourceManager.GetString("Message_ServeNeedsApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job&apos;s options are not valid: {0}.
        /// </summary>
        public static string Message_ServeOptionsNotValid {
            get {
                return ResourceManager.GetString("Message_ServeOptionsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plan&apos;s file needs a name: the job&apos;s outputs are named after it..
        /// </summary>
        public static string Message_ServePlanNeedsName {
            get {
                return ResourceManager.GetString("Message_ServePlanNeedsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it does not match the job zpp sent..
        /// </summary>
        public static string Message_ServerAnswerDoesNotMatchJob {
            get {
                return ResourceManager.GetString("Message_ServerAnswerDoesNotMatchJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server at {0} gave an answer zpp cannot read: {1}.
        /// </summary>
        public static string Message_ServerAnswerNotValid {
            get {
                return ResourceManager.GetString("Message_ServerAnswerNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zpp serve imports .xlsx files only: to import {0}, run zpp without {1}..
        /// </summary>
        public static string Message_ServerCannotImport {
            get {
                return ResourceManager.GetString("Message_ServerCannotImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send one plan: as a file named &apos;input&apos;, or named &apos;import&apos; to import it..
        /// </summary>
        public static string Message_ServeRequestNeedsPlan {
            get {
                return ResourceManager.GetString("Message_ServeRequestNeedsPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the job as multipart/form-data: the plan as a file named &apos;input&apos;, or &apos;import&apos; to import it, and its options in a part named &apos;options&apos;..
        /// </summary>
        public static string Message_ServeRequestNotMultipart {
            get {
                return ResourceManager.GetString("Message_ServeRequestNotMultipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be read: {0}.
        /// </summary>
        public static string Message_ServeRequestNotReadable {
            get {
                return ResourceManager.GetString("Message_ServeRequestNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is larger than the {0} MB the server accepts..
        /// </summary>
        public static string Message_ServeRequestTooLarge {
            get {
                return ResourceManager.GetString("Message_ServeRequestTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is set, so zpp runs on a server, which imports .xlsx files only: to import {1}, use {2}..
        /// </summary>
        public static string Message_ServerFromEnvironmentCannotImport {
            get {
                return ResourceManager.GetString("Message_ServerFromEnvironmentCannotImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server at {0} needs its API key: set {1}, or use {2}..
        /// </summary>
        public static string Message_ServerNeedsApiKey {
            get {
                return ResourceManager.GetString("Message_ServerNeedsApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;, from {1}, is not a server zpp can run on: give its http or https address, such as http://localhost:9770, or unix: and the path of its socket..
        /// </summary>
        public static string Message_ServerNotValid {
            get {
                return ResourceManager.GetString("Message_ServerNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server at {0} did not run the job: {1}.
        /// </summary>
        public static string Message_ServerRefused {
            get {
                return ResourceManager.GetString("Message_ServerRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server at {0} did not accept the API key..
        /// </summary>
        public static string Message_ServerRefusedApiKey {
            get {
                return ResourceManager.GetString("Message_ServerRefusedApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no socket at {0}..
        /// </summary>
        public static string Message_ServerSocketNotThere {
            get {
                return ResourceManager.GetString("Message_ServerSocketNotThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server at {0} was still busy after {1} seconds, so the job did not run..
        /// </summary>
        public static string Message_ServerStayedBusy {
            get {
                return ResourceManager.GetString("Message_ServerStayedBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zpp could not reach the server at {0}: {1}.
        /// </summary>
        public static string Message_ServerUnreachable {
            get {
                return ResourceManager.GetString("Message_ServerUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;scenario&apos; is only valid with a plan sent as &apos;input&apos;..
        /// </summary>
        public static string Message_ServeScenarioOnlyWithInput {
            get {
                return ResourceManager.GetString("Message_ServeScenarioOnlyWithInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the project as a file named &apos;input&apos;..
        /// </summary>
        public static string Message_ServeScenariosNeedInput {
            get {
                return ResourceManager.GetString("Message_ServeScenariosNeedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limits in {0} or in the {1} environment variables could not be read: {2}.
        /// </summary>
        public static string Message_ServeSettingsNotValid {
            get {
                return ResourceManager.GetString("Message_ServeSettingsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs the path of the socket to listen on..
        /// </summary>
        public static string Message_ServeUnixSocketNeedsPath {
            get {
                return ResourceManager.GetString("Message_ServeUnixSocketNeedsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; matches {1} scenarios - use {2} and select one by id.
        /// </summary>
        public static string Message_SeveralScenariosMatch {
            get {
                return ResourceManager.GetString("Message_SeveralScenariosMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; matches {1} scenarios.
        /// </summary>
        public static string Message_SeveralScenariosMatchSelector {
            get {
                return ResourceManager.GetString("Message_SeveralScenariosMatchSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slack Limit must be equal or greater than 0.
        /// </summary>
        public static string Message_SlackLimitMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_SlackLimitMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify either {0} or {1}, but not both..
        /// </summary>
        public static string Message_SpecifyEitherOptionNotBoth {
            get {
                return ResourceManager.GetString("Message_SpecifyEitherOptionNotBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is loading....
        /// </summary>
        public static string Message_SplashScreenLoading {
            get {
                return ResourceManager.GetString("Message_SplashScreenLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag already exists.
        /// </summary>
        public static string Message_TagAlreadyExists {
            get {
                return ResourceManager.GetString("Message_TagAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag cannot be empty.
        /// </summary>
        public static string Message_TagCannotBeEmpty {
            get {
                return ResourceManager.GetString("Message_TagCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Count must be equal or greater than 0.
        /// </summary>
        public static string Message_TrackerCountMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_TrackerCountMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine directory for Dock Layout.
        /// </summary>
        public static string Message_UnableToDetermineDockLayoutDirectory {
            get {
                return ResourceManager.GetString("Message_UnableToDetermineDockLayoutDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine folder path for product settings.
        /// </summary>
        public static string Message_UnableToDetermineProductSettingsFolderPath {
            get {
                return ResourceManager.GetString("Message_UnableToDetermineProductSettingsFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine directory for User Settings.
        /// </summary>
        public static string Message_UnableToDetermineUserSettingsDirectory {
            get {
                return ResourceManager.GetString("Message_UnableToDetermineUserSettingsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to export file:.
        /// </summary>
        public static string Message_UnableToExportFile {
            get {
                return ResourceManager.GetString("Message_UnableToExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import file:.
        /// </summary>
        public static string Message_UnableToImportFile {
            get {
                return ResourceManager.GetString("Message_UnableToImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file:.
        /// </summary>
        public static string Message_UnableToOpenFile {
            get {
                return ResourceManager.GetString("Message_UnableToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve type:.
        /// </summary>
        public static string Message_UnableToResolveType {
            get {
                return ResourceManager.GetString("Message_UnableToResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file:.
        /// </summary>
        public static string Message_UnableToSaveFile {
            get {
                return ResourceManager.GetString("Message_UnableToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Billing must be equal to or greater than 0 .
        /// </summary>
        public static string Message_UnitBillingMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("Message_UnitBillingMustBeZeroOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost must be equal to or greater than 0.
        /// </summary>
        public static string Message_UnitCostMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("Message_UnitCostMustBeZeroOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown AllocationMode value:.
        /// </summary>
        public static string Message_UnknownAllocationMode {
            get {
                return ResourceManager.GetString("Message_UnknownAllocationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown CurveFittingType value:.
        /// </summary>
        public static string Message_UnknownCurveFittingType {
            get {
                return ResourceManager.GetString("Message_UnknownCurveFittingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown DateTimeDisplayMode value:.
        /// </summary>
        public static string Message_UnknownDateTimeDisplayMode {
            get {
                return ResourceManager.GetString("Message_UnknownDateTimeDisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown DisplayStyle value:.
        /// </summary>
        public static string Message_UnknownDisplayStyle {
            get {
                return ResourceManager.GetString("Message_UnknownDisplayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown GroupByMode value:.
        /// </summary>
        public static string Message_UnknownGroupByMode {
            get {
                return ResourceManager.GetString("Message_UnknownGroupByMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown NonWorkingDayMode value:.
        /// </summary>
        public static string Message_UnknownNonWorkingDayMode {
            get {
                return ResourceManager.GetString("Message_UnknownNonWorkingDayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file: unknown version &apos;{0}&apos;.
        /// </summary>
        public static string Message_UnknownProjectFileVersion {
            get {
                return ResourceManager.GetString("Message_UnknownProjectFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ScheduleMode value:.
        /// </summary>
        public static string Message_UnknownScheduleMode {
            get {
                return ResourceManager.GetString("Message_UnknownScheduleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SortMode value:.
        /// </summary>
        public static string Message_UnknownSortDirection {
            get {
                return ResourceManager.GetString("Message_UnknownSortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SortDirection value:.
        /// </summary>
        public static string Message_UnknownSortMode {
            get {
                return ResourceManager.GetString("Message_UnknownSortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown TrackedMetric value:.
        /// </summary>
        public static string Message_UnknownTrackedMetric {
            get {
                return ResourceManager.GetString("Message_UnknownTrackedMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex graph cannot contain Normal nodes without any End nodes.
        /// </summary>
        public static string Message_VertexGraphCannotContainNormalNodesWithoutAnyEndNodes {
            get {
                return ResourceManager.GetString("Message_VertexGraphCannotContainNormalNodesWithoutAnyEndNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex graph cannot contain Normal nodes without any Start nodes.
        /// </summary>
        public static string Message_VertexGraphCannotContainNormalNodesWithoutAnyStartNodes {
            get {
                return ResourceManager.GetString("Message_VertexGraphCannotContainNormalNodesWithoutAnyStartNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Graph Data contains no End nodes.
        /// </summary>
        public static string Message_VertexGraphDataContainsNoEndNodes {
            get {
                return ResourceManager.GetString("Message_VertexGraphDataContainsNoEndNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Graph Data contains no Start nodes.
        /// </summary>
        public static string Message_VertexGraphDataContainsNoStartNodes {
            get {
                return ResourceManager.GetString("Message_VertexGraphDataContainsNoStartNodes", resourceCulture);
            }
        }
    }
}
