//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph Data contain more than one End node.
        /// </summary>
        public static string Message_ArrowGraphDataContainMultipleEndNodes {
            get {
                return ResourceManager.GetString("Message_ArrowGraphDataContainMultipleEndNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph Data contain more than one Start node.
        /// </summary>
        public static string Message_ArrowGraphDataContainMultipleStartNodes {
            get {
                return ResourceManager.GetString("Message_ArrowGraphDataContainMultipleStartNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build arrow graph.
        /// </summary>
        public static string Message_CannotBuildArrowGraph {
            get {
                return ResourceManager.GetString("Message_CannotBuildArrowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnType must be derived from DataGridColumn.
        /// </summary>
        public static string Message_ColumnTypeMustBeDerivedFromDataGridColumn {
            get {
                return ResourceManager.GetString("Message_ColumnTypeMustBeDerivedFromDataGridColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation errors.
        /// </summary>
        public static string Message_CompilationErrors {
            get {
                return ResourceManager.GetString("Message_CompilationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticality Weight must be equal or greater than 0.
        /// </summary>
        public static string Message_CriticalityWeightMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_CriticalityWeightMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty filename.
        /// </summary>
        public static string Message_EmptyFilename {
            get {
                return ResourceManager.GetString("Message_EmptyFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci Weight must be equal or greater than 0.
        /// </summary>
        public static string Message_FibonacciWeightMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_FibonacciWeightMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by head Nodes do not match when building Arrow Graph.
        /// </summary>
        public static string Message_MismatchedEdgeIdsForHeadNodes {
            get {
                return ResourceManager.GetString("Message_MismatchedEdgeIdsForHeadNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by tail Nodes do not match when building Arrow Graph.
        /// </summary>
        public static string Message_MismatchedEdgeIdsForTailNodes {
            get {
                return ResourceManager.GetString("Message_MismatchedEdgeIdsForTailNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Node IDs and Nodes associated with Edges do not match when building Arrow Graph.
        /// </summary>
        public static string Message_MismatchedNodeIdsAssociatedWithEdges {
            get {
                return ResourceManager.GetString("Message_MismatchedNodeIdsAssociatedWithEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Trackers must be equal or greater than 0.
        /// </summary>
        public static string Message_NewTrackersMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_NewTrackersMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Window icon available.
        /// </summary>
        public static string Message_NoWindowIconAvailable {
            get {
                return ResourceManager.GetString("Message_NoWindowIconAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of Trackers across all Activities is not identical.
        /// </summary>
        public static string Message_NumberOfTrackersAcrossAllActivitiesNotIdentical {
            get {
                return ResourceManager.GetString("Message_NumberOfTrackersAcrossAllActivitiesNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slack Limit must be equal or greater than 0.
        /// </summary>
        public static string Message_SlackLimitMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_SlackLimitMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is loading....
        /// </summary>
        public static string Message_SplashScreenLoading {
            get {
                return ResourceManager.GetString("Message_SplashScreenLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Count must be equal or greater than 0.
        /// </summary>
        public static string Message_TrackerCountMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_TrackerCountMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine file path for User Secrets.
        /// </summary>
        public static string Message_UnableToDetermineUserSecretsPath {
            get {
                return ResourceManager.GetString("Message_UnableToDetermineUserSecretsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to export file:.
        /// </summary>
        public static string Message_UnableToExportFile {
            get {
                return ResourceManager.GetString("Message_UnableToExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import file:.
        /// </summary>
        public static string Message_UnableToImportFile {
            get {
                return ResourceManager.GetString("Message_UnableToImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file:.
        /// </summary>
        public static string Message_UnableToOpenFile {
            get {
                return ResourceManager.GetString("Message_UnableToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve type:.
        /// </summary>
        public static string Message_UnableToResolveType {
            get {
                return ResourceManager.GetString("Message_UnableToResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file:.
        /// </summary>
        public static string Message_UnableToSaveFile {
            get {
                return ResourceManager.GetString("Message_UnableToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost must be greater than 0.
        /// </summary>
        public static string Message_UnitCostMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_UnitCostMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown DateTimeCalculatorMode value:.
        /// </summary>
        public static string Message_UnknownDateTimeCalculatorMode {
            get {
                return ResourceManager.GetString("Message_UnknownDateTimeCalculatorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown DateTimeDisplayMode value:.
        /// </summary>
        public static string Message_UnknownDateTimeDisplayMode {
            get {
                return ResourceManager.GetString("Message_UnknownDateTimeDisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown EdgeDashStyle value.
        /// </summary>
        public static string Message_UnknownEdgeDashStyleValue {
            get {
                return ResourceManager.GetString("Message_UnknownEdgeDashStyleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has unsaved changes. Do you wish to continue?.
        /// </summary>
        public static string Message_UnsavedChanges {
            get {
                return ResourceManager.GetString("Message_UnsavedChanges", resourceCulture);
            }
        }
    }
}
