//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag to node.
        /// </summary>
        public static string Message_AddTag {
            get {
                return ResourceManager.GetString("Message_AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph Data contain more than one End node.
        /// </summary>
        public static string Message_ArrowGraphDataContainMultipleEndNodes {
            get {
                return ResourceManager.GetString("Message_ArrowGraphDataContainMultipleEndNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph Data contain more than one Start node.
        /// </summary>
        public static string Message_ArrowGraphDataContainMultipleStartNodes {
            get {
                return ResourceManager.GetString("Message_ArrowGraphDataContainMultipleStartNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} cannot both be set.
        /// </summary>
        public static string Message_CannotBothBeSet {
            get {
                return ResourceManager.GetString("Message_CannotBothBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build arrow graph.
        /// </summary>
        public static string Message_CannotBuildArrowGraph {
            get {
                return ResourceManager.GetString("Message_CannotBuildArrowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a project scenario file from a folder node:.
        /// </summary>
        public static string Message_CannotGetProjectScenarioFileFromFolderNode {
            get {
                return ResourceManager.GetString("Message_CannotGetProjectScenarioFileFromFolderNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a project scenario file when project scenario is null:.
        /// </summary>
        public static string Message_CannotGetProjectScenarioFileWhenProjectScenarioIsNull {
            get {
                return ResourceManager.GetString("Message_CannotGetProjectScenarioFileWhenProjectScenarioIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a project scenario on a folder node:.
        /// </summary>
        public static string Message_CannotSetProjectScenarioOnFolderNode {
            get {
                return ResourceManager.GetString("Message_CannotSetProjectScenarioOnFolderNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot track a project scenario file from a folder node:.
        /// </summary>
        public static string Message_CannotTrackProjectScenarioFileFromFolderNode {
            get {
                return ResourceManager.GetString("Message_CannotTrackProjectScenarioFileFromFolderNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnType must be derived from DataGridColumn.
        /// </summary>
        public static string Message_ColumnTypeMustBeDerivedFromDataGridColumn {
            get {
                return ResourceManager.GetString("Message_ColumnTypeMustBeDerivedFromDataGridColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation errors.
        /// </summary>
        public static string Message_CompilationErrors {
            get {
                return ResourceManager.GetString("Message_CompilationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted from previous version.
        /// </summary>
        public static string Message_ConvertedFromPreviousVersion {
            get {
                return ResourceManager.GetString("Message_ConvertedFromPreviousVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticality Weight must be equal or greater than 0.
        /// </summary>
        public static string Message_CriticalityWeightMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_CriticalityWeightMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Day.
        /// </summary>
        public static string Message_DefaultChristmasDayName {
            get {
                return ResourceManager.GetString("Message_DefaultChristmasDayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas holiday.
        /// </summary>
        public static string Message_DefaultChristmasDayNotes {
            get {
                return ResourceManager.GetString("Message_DefaultChristmasDayNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year&apos;s Day.
        /// </summary>
        public static string Message_DefaultNewYearsDayName {
            get {
                return ResourceManager.GetString("Message_DefaultNewYearsDayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year&apos;s holiday.
        /// </summary>
        public static string Message_DefaultNewYearsDayNotes {
            get {
                return ResourceManager.GetString("Message_DefaultNewYearsDayNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekends.
        /// </summary>
        public static string Message_DefaultWeekendsName {
            get {
                return ResourceManager.GetString("Message_DefaultWeekendsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekends off.
        /// </summary>
        public static string Message_DefaultWeekendsNotes {
            get {
                return ResourceManager.GetString("Message_DefaultWeekendsNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tag from node.
        /// </summary>
        public static string Message_DeleteTag {
            get {
                return ResourceManager.GetString("Message_DeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete these items?.
        /// </summary>
        public static string Message_DoYouWishToDeleteTheseItems {
            get {
                return ResourceManager.GetString("Message_DoYouWishToDeleteTheseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate RRULE part: &apos;{0}&apos;.
        /// </summary>
        public static string Message_DuplicateRRulePart {
            get {
                return ResourceManager.GetString("Message_DuplicateRRulePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the properties to edit.
        /// </summary>
        public static string Message_EditActivities {
            get {
                return ResourceManager.GetString("Message_EditActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the properties to edit.
        /// </summary>
        public static string Message_EditResources {
            get {
                return ResourceManager.GetString("Message_EditResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty filename.
        /// </summary>
        public static string Message_EmptyFilename {
            get {
                return ResourceManager.GetString("Message_EmptyFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci Weight must be equal or greater than 0.
        /// </summary>
        public static string Message_FibonacciWeightMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_FibonacciWeightMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Billing must be equal to or greater than 0 .
        /// </summary>
        public static string Message_FixedBillingMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("Message_FixedBillingMustBeZeroOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Cost must be equal to or greater than 0.
        /// </summary>
        public static string Message_FixedCostMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("Message_FixedCostMustBeZeroOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Frequency value: &apos;{0}&apos;.
        /// </summary>
        public static string Message_InvalidFrequencyValue {
            get {
                return ResourceManager.GetString("Message_InvalidFrequencyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} value: &apos;{1}&apos;.
        /// </summary>
        public static string Message_InvalidInputValue {
            get {
                return ResourceManager.GetString("Message_InvalidInputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RRULE part: &apos;{0}&apos;.
        /// </summary>
        public static string Message_InvalidRRulePart {
            get {
                return ResourceManager.GetString("Message_InvalidRRulePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid weekday value: &apos;{0}&apos;.
        /// </summary>
        public static string Message_InvalidWeekdayValue {
            get {
                return ResourceManager.GetString("Message_InvalidWeekdayValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by head Nodes do not match when building Arrow Graph.
        /// </summary>
        public static string Message_MismatchedEdgeIdsForHeadNodesInArrowGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedEdgeIdsForHeadNodesInArrowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by head Nodes do not match when building Vertex Graph.
        /// </summary>
        public static string Message_MismatchedEdgeIdsForHeadNodesInVertexGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedEdgeIdsForHeadNodesInVertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by tail Nodes do not match when building Arrow Graph.
        /// </summary>
        public static string Message_MismatchedEdgeIdsForTailNodesInArrowGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedEdgeIdsForTailNodesInArrowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by tail Nodes do not match when building Vertex Graph.
        /// </summary>
        public static string Message_MismatchedEdgeIdsForTailNodesInVertexGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedEdgeIdsForTailNodesInVertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Node IDs and Nodes associated with Edges do not match when building Arrow Graph.
        /// </summary>
        public static string Message_MismatchedNodeIdsAssociatedWithEdgesInArrowGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedNodeIdsAssociatedWithEdgesInArrowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Node IDs and Nodes associated with Edges do not match when building Vertex Graph.
        /// </summary>
        public static string Message_MismatchedNodeIdsAssociatedWithEdgesInVertexGraph {
            get {
                return ResourceManager.GetString("Message_MismatchedNodeIdsAssociatedWithEdgesInVertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than zero ({1}).
        /// </summary>
        public static string Message_MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_MustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be either -1 or greater than zero.
        /// </summary>
        public static string Message_MustBeMinusOneOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_MustBeMinusOneOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        public static string Message_NameAlreadyExists {
            get {
                return ResourceManager.GetString("Message_NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        public static string Message_NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("Message_NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Trackers must be equal or greater than 0.
        /// </summary>
        public static string Message_NewTrackersMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_NewTrackersMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Window icon available.
        /// </summary>
        public static string Message_NoWindowIconAvailable {
            get {
                return ResourceManager.GetString("Message_NoWindowIconAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of Trackers across all Activities is not identical.
        /// </summary>
        public static string Message_NumberOfTrackersAcrossAllActivitiesNotIdentical {
            get {
                return ResourceManager.GetString("Message_NumberOfTrackersAcrossAllActivitiesNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has unsaved changes. Do you wish to continue?.
        /// </summary>
        public static string Message_ProjectUnsavedChanges {
            get {
                return ResourceManager.GetString("Message_ProjectUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RRule must contain &apos;{0}&apos;.
        /// </summary>
        public static string Message_RRuleMustContain {
            get {
                return ResourceManager.GetString("Message_RRuleMustContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario has unsaved changes. Do you wish to continue?.
        /// </summary>
        public static string Message_ScenarioUnsavedChanges {
            get {
                return ResourceManager.GetString("Message_ScenarioUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slack Limit must be equal or greater than 0.
        /// </summary>
        public static string Message_SlackLimitMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_SlackLimitMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is loading....
        /// </summary>
        public static string Message_SplashScreenLoading {
            get {
                return ResourceManager.GetString("Message_SplashScreenLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag already exists.
        /// </summary>
        public static string Message_TagAlreadyExists {
            get {
                return ResourceManager.GetString("Message_TagAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag cannot be empty.
        /// </summary>
        public static string Message_TagCannotBeEmpty {
            get {
                return ResourceManager.GetString("Message_TagCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Count must be equal or greater than 0.
        /// </summary>
        public static string Message_TrackerCountMustBeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("Message_TrackerCountMustBeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine file directory for User Settings.
        /// </summary>
        public static string Message_UnableToDetermineUserSettingsDirectory {
            get {
                return ResourceManager.GetString("Message_UnableToDetermineUserSettingsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine file path for User Settings.
        /// </summary>
        public static string Message_UnableToDetermineUserSettingsPath {
            get {
                return ResourceManager.GetString("Message_UnableToDetermineUserSettingsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to export file:.
        /// </summary>
        public static string Message_UnableToExportFile {
            get {
                return ResourceManager.GetString("Message_UnableToExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import file:.
        /// </summary>
        public static string Message_UnableToImportFile {
            get {
                return ResourceManager.GetString("Message_UnableToImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file:.
        /// </summary>
        public static string Message_UnableToOpenFile {
            get {
                return ResourceManager.GetString("Message_UnableToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve type:.
        /// </summary>
        public static string Message_UnableToResolveType {
            get {
                return ResourceManager.GetString("Message_UnableToResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file:.
        /// </summary>
        public static string Message_UnableToSaveFile {
            get {
                return ResourceManager.GetString("Message_UnableToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Billing must be equal to or greater than 0 .
        /// </summary>
        public static string Message_UnitBillingMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("Message_UnitBillingMustBeZeroOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost must be equal to or greater than 0.
        /// </summary>
        public static string Message_UnitCostMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("Message_UnitCostMustBeZeroOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown AllocationMode value:.
        /// </summary>
        public static string Message_UnknownAllocationMode {
            get {
                return ResourceManager.GetString("Message_UnknownAllocationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown CurveFittingType value:.
        /// </summary>
        public static string Message_UnknownCurveFittingType {
            get {
                return ResourceManager.GetString("Message_UnknownCurveFittingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown DateTimeDisplayMode value:.
        /// </summary>
        public static string Message_UnknownDateTimeDisplayMode {
            get {
                return ResourceManager.GetString("Message_UnknownDateTimeDisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown DisplayStyle value:.
        /// </summary>
        public static string Message_UnknownDisplayStyle {
            get {
                return ResourceManager.GetString("Message_UnknownDisplayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown EdgeDashStyle value.
        /// </summary>
        public static string Message_UnknownEdgeDashStyleValue {
            get {
                return ResourceManager.GetString("Message_UnknownEdgeDashStyleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown GroupByMode value:.
        /// </summary>
        public static string Message_UnknownGroupByMode {
            get {
                return ResourceManager.GetString("Message_UnknownGroupByMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown NodeBorderDashStyle value.
        /// </summary>
        public static string Message_UnknownNodeBorderDashStyleValue {
            get {
                return ResourceManager.GetString("Message_UnknownNodeBorderDashStyleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown NonWorkingDayMode value:.
        /// </summary>
        public static string Message_UnknownNonWorkingDayMode {
            get {
                return ResourceManager.GetString("Message_UnknownNonWorkingDayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ScheduleMode value:.
        /// </summary>
        public static string Message_UnknownScheduleMode {
            get {
                return ResourceManager.GetString("Message_UnknownScheduleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SortMode value:.
        /// </summary>
        public static string Message_UnknownSortDirection {
            get {
                return ResourceManager.GetString("Message_UnknownSortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SortDirection value:.
        /// </summary>
        public static string Message_UnknownSortMode {
            get {
                return ResourceManager.GetString("Message_UnknownSortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown TrackedMetric value:.
        /// </summary>
        public static string Message_UnknownTrackedMetric {
            get {
                return ResourceManager.GetString("Message_UnknownTrackedMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex graph cannot contain Normal nodes without any End nodes.
        /// </summary>
        public static string Message_VertexGraphCannotContainNormalNodesWithoutAnyEndNodes {
            get {
                return ResourceManager.GetString("Message_VertexGraphCannotContainNormalNodesWithoutAnyEndNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex graph cannot contain Normal nodes without any Start nodes.
        /// </summary>
        public static string Message_VertexGraphCannotContainNormalNodesWithoutAnyStartNodes {
            get {
                return ResourceManager.GetString("Message_VertexGraphCannotContainNormalNodesWithoutAnyStartNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Graph Data contains no End nodes.
        /// </summary>
        public static string Message_VertexGraphDataContainsNoEndNodes {
            get {
                return ResourceManager.GetString("Message_VertexGraphDataContainsNoEndNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Graph Data contains no Start nodes.
        /// </summary>
        public static string Message_VertexGraphDataContainsNoStartNodes {
            get {
                return ResourceManager.GetString("Message_VertexGraphDataContainsNoStartNodes", resourceCulture);
            }
        }
    }
}
