//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reporting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reporting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Reporting", typeof(Reporting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Reporting_Time {
            get {
                return ResourceManager.GetString("Reporting_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Reporting_WorksheetActivities {
            get {
                return ResourceManager.GetString("Reporting_WorksheetActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Severities.
        /// </summary>
        public static string Reporting_WorksheetActivitySeverities {
            get {
                return ResourceManager.GetString("Reporting_WorksheetActivitySeverities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Tracker.
        /// </summary>
        public static string Reporting_WorksheetActivityTracker {
            get {
                return ResourceManager.GetString("Reporting_WorksheetActivityTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned-Value.
        /// </summary>
        public static string Reporting_WorksheetEarnedValue {
            get {
                return ResourceManager.GetString("Reporting_WorksheetEarnedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned-Value Chart (Effort).
        /// </summary>
        public static string Reporting_WorksheetEarnedValueChartEffort {
            get {
                return ResourceManager.GetString("Reporting_WorksheetEarnedValueChartEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned-Value Chart (Plan).
        /// </summary>
        public static string Reporting_WorksheetEarnedValueChartPlan {
            get {
                return ResourceManager.GetString("Reporting_WorksheetEarnedValueChartPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned-Value Chart (Progress).
        /// </summary>
        public static string Reporting_WorksheetEarnedValueChartProgress {
            get {
                return ResourceManager.GetString("Reporting_WorksheetEarnedValueChartProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Reporting_WorksheetGeneral {
            get {
                return ResourceManager.GetString("Reporting_WorksheetGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources Allocations.
        /// </summary>
        public static string Reporting_WorksheetResourceAllocations {
            get {
                return ResourceManager.GetString("Reporting_WorksheetResourceAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Chart (Costs).
        /// </summary>
        public static string Reporting_WorksheetResourceChartCosts {
            get {
                return ResourceManager.GetString("Reporting_WorksheetResourceChartCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Chart (Data).
        /// </summary>
        public static string Reporting_WorksheetResourceChartData {
            get {
                return ResourceManager.GetString("Reporting_WorksheetResourceChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Reporting_WorksheetResources {
            get {
                return ResourceManager.GetString("Reporting_WorksheetResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Tracker.
        /// </summary>
        public static string Reporting_WorksheetResourceTracker {
            get {
                return ResourceManager.GetString("Reporting_WorksheetResourceTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Streams.
        /// </summary>
        public static string Reporting_WorksheetWorkStreams {
            get {
                return ResourceManager.GetString("Reporting_WorksheetWorkStreams", resourceCulture);
            }
        }
    }
}
