//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Title_ActivitiesView {
            get {
                return ResourceManager.GetString("Title_ActivitiesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph Settings.
        /// </summary>
        public static string Title_ArrowGraphSettingsView {
            get {
                return ResourceManager.GetString("Title_ArrowGraphSettingsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph.
        /// </summary>
        public static string Title_ArrowGraphView {
            get {
                return ResourceManager.GetString("Title_ArrowGraphView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned-Value Chart.
        /// </summary>
        public static string Title_EarnedValueChartView {
            get {
                return ResourceManager.GetString("Title_EarnedValueChartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gantt Chart.
        /// </summary>
        public static string Title_GanttChartView {
            get {
                return ResourceManager.GetString("Title_GanttChartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string Title_Metrics {
            get {
                return ResourceManager.GetString("Title_Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Title_Output {
            get {
                return ResourceManager.GetString("Title_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectplan.net.
        /// </summary>
        public static string Title_ProjectPlan {
            get {
                return ResourceManager.GetString("Title_ProjectPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Chart.
        /// </summary>
        public static string Title_ResourceChartView {
            get {
                return ResourceManager.GetString("Title_ResourceChartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Settings.
        /// </summary>
        public static string Title_ResourceSettingsView {
            get {
                return ResourceManager.GetString("Title_ResourceSettingsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Title_TrackingView {
            get {
                return ResourceManager.GetString("Title_TrackingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has unsaved changes.
        /// </summary>
        public static string Title_UnsavedChanges {
            get {
                return ResourceManager.GetString("Title_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Title_UntitledProject {
            get {
                return ResourceManager.GetString("Title_UntitledProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string Title_Values {
            get {
                return ResourceManager.GetString("Title_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Stream Settings.
        /// </summary>
        public static string Title_WorkStreamSettingsView {
            get {
                return ResourceManager.GetString("Title_WorkStreamSettingsView", resourceCulture);
            }
        }
    }
}
