//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Resource.ProjectPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Resource.ProjectPlan.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Name.
        /// </summary>
        public static string ToolTip_ActivityName {
            get {
                return ResourceManager.GetString("ToolTip_ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated to Resources.
        /// </summary>
        public static string ToolTip_AllocatedToResources {
            get {
                return ResourceManager.GetString("ToolTip_AllocatedToResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ToolTip_ColorFormat {
            get {
                return ResourceManager.GetString("ToolTip_ColorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticality Weight.
        /// </summary>
        public static string ToolTip_CriticalityWeight {
            get {
                return ResourceManager.GetString("ToolTip_CriticalityWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string ToolTip_Dependencies {
            get {
                return ResourceManager.GetString("ToolTip_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string ToolTip_DisplayOrder {
            get {
                return ResourceManager.GetString("ToolTip_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string ToolTip_Duration {
            get {
                return ResourceManager.GetString("ToolTip_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest Finish Time.
        /// </summary>
        public static string ToolTip_EarliestFinishTime {
            get {
                return ResourceManager.GetString("ToolTip_EarliestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest Start Time.
        /// </summary>
        public static string ToolTip_EarliestStartTime {
            get {
                return ResourceManager.GetString("ToolTip_EarliestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci Weight.
        /// </summary>
        public static string ToolTip_FibonacciWeight {
            get {
                return ResourceManager.GetString("ToolTip_FibonacciWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string ToolTip_Find {
            get {
                return ResourceManager.GetString("ToolTip_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Slack.
        /// </summary>
        public static string ToolTip_FreeSlack {
            get {
                return ResourceManager.GetString("ToolTip_FreeSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Cost.
        /// </summary>
        public static string ToolTip_HasNoCost {
            get {
                return ResourceManager.GetString("ToolTip_HasNoCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string ToolTip_Id {
            get {
                return ResourceManager.GetString("ToolTip_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter-activity Allocation.
        /// </summary>
        public static string ToolTip_InterActivityAllocationType {
            get {
                return ResourceManager.GetString("ToolTip_InterActivityAllocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter-activity Phases.
        /// </summary>
        public static string ToolTip_InterActivityPhases {
            get {
                return ResourceManager.GetString("ToolTip_InterActivityPhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfering Slack.
        /// </summary>
        public static string ToolTip_InterferingSlack {
            get {
                return ResourceManager.GetString("ToolTip_InterferingSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Activity.
        /// </summary>
        public static string ToolTip_IsCritical {
            get {
                return ResourceManager.GetString("ToolTip_IsCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy Activity.
        /// </summary>
        public static string ToolTip_IsDummy {
            get {
                return ResourceManager.GetString("ToolTip_IsDummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit Target.
        /// </summary>
        public static string ToolTip_IsExplicitTarget {
            get {
                return ResourceManager.GetString("ToolTip_IsExplicitTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string ToolTip_IsInactive {
            get {
                return ResourceManager.GetString("ToolTip_IsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        public static string ToolTip_IsPhase {
            get {
                return ResourceManager.GetString("ToolTip_IsPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Finish Time.
        /// </summary>
        public static string ToolTip_LatestFinishTime {
            get {
                return ResourceManager.GetString("ToolTip_LatestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Start Time.
        /// </summary>
        public static string ToolTip_LatestStartTime {
            get {
                return ResourceManager.GetString("ToolTip_LatestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Latest Finish Time.
        /// </summary>
        public static string ToolTip_MaximumLatestFinishTime {
            get {
                return ResourceManager.GetString("ToolTip_MaximumLatestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Earliest Start Time.
        /// </summary>
        public static string ToolTip_MinimumEarliestStartTime {
            get {
                return ResourceManager.GetString("ToolTip_MinimumEarliestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Free Slack.
        /// </summary>
        public static string ToolTip_MinimumFreeSlack {
            get {
                return ResourceManager.GetString("ToolTip_MinimumFreeSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ToolTip_Notes {
            get {
                return ResourceManager.GetString("ToolTip_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Completed.
        /// </summary>
        public static string ToolTip_PercentageCompleted {
            get {
                return ResourceManager.GetString("ToolTip_PercentageCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Dependencies.
        /// </summary>
        public static string ToolTip_ResourceDependencies {
            get {
                return ResourceManager.GetString("ToolTip_ResourceDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Name.
        /// </summary>
        public static string ToolTip_ResourceName {
            get {
                return ResourceManager.GetString("ToolTip_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slack Limit.
        /// </summary>
        public static string ToolTip_SlackLimit {
            get {
                return ResourceManager.GetString("ToolTip_SlackLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Operator.
        /// </summary>
        public static string ToolTip_TargetResourceOperator {
            get {
                return ResourceManager.GetString("ToolTip_TargetResourceOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Resources.
        /// </summary>
        public static string ToolTip_TargetResources {
            get {
                return ResourceManager.GetString("ToolTip_TargetResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Work Streams.
        /// </summary>
        public static string ToolTip_TargetWorkStreams {
            get {
                return ResourceManager.GetString("ToolTip_TargetWorkStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Slack.
        /// </summary>
        public static string ToolTip_TotalSlack {
            get {
                return ResourceManager.GetString("ToolTip_TotalSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string ToolTip_UnitCost {
            get {
                return ResourceManager.GetString("ToolTip_UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Stream Name.
        /// </summary>
        public static string ToolTip_WorkStreamName {
            get {
                return ResourceManager.GetString("ToolTip_WorkStreamName", resourceCulture);
            }
        }
    }
}
