//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Graphs.Avalonia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Graphs.Avalonia.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_EdgeRouting_None {
            get {
                return ResourceManager.GetString("Enum_EdgeRouting_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectilinear.
        /// </summary>
        public static string Enum_EdgeRouting_Rectilinear {
            get {
                return ResourceManager.GetString("Enum_EdgeRouting_Rectilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectilinear to Center.
        /// </summary>
        public static string Enum_EdgeRouting_RectilinearToCenter {
            get {
                return ResourceManager.GetString("Enum_EdgeRouting_RectilinearToCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spline.
        /// </summary>
        public static string Enum_EdgeRouting_Spline {
            get {
                return ResourceManager.GetString("Enum_EdgeRouting_Spline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spline Bundling.
        /// </summary>
        public static string Enum_EdgeRouting_SplineBundling {
            get {
                return ResourceManager.GetString("Enum_EdgeRouting_SplineBundling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Line.
        /// </summary>
        public static string Enum_EdgeRouting_StraightLine {
            get {
                return ResourceManager.GetString("Enum_EdgeRouting_StraightLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugiyama Splines.
        /// </summary>
        public static string Enum_EdgeRouting_SugiyamaSplines {
            get {
                return ResourceManager.GetString("Enum_EdgeRouting_SugiyamaSplines", resourceCulture);
            }
        }
    }
}
