//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://graphml.graphdrawing.org/xmlns", IsNullable=false)]
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
public partial class data {
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.

    private string resourcesField;
    
    private ShapeNode shapeNodeField;
    
    private PolyLineEdge polyLineEdgeField;
    
    private string keyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.yworks.com/xml/graphml")]
    public string Resources {
        get {
            return this.resourcesField;
        }
        set {
            this.resourcesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.yworks.com/xml/graphml")]
    public ShapeNode ShapeNode {
        get {
            return this.shapeNodeField;
        }
        set {
            this.shapeNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.yworks.com/xml/graphml")]
    public PolyLineEdge PolyLineEdge {
        get {
            return this.polyLineEdgeField;
        }
        set {
            this.polyLineEdgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.yworks.com/xml/graphml", IsNullable=false)]
public partial class ShapeNode {
    
    private ShapeNodeGeometry geometryField;
    
    private ShapeNodeFill fillField;
    
    private ShapeNodeBorderStyle borderStyleField;
    
    private ShapeNodeNodeLabel nodeLabelField;
    
    private ShapeNodeShape shapeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Geometry")]
    public ShapeNodeGeometry Geometry {
        get {
            return this.geometryField;
        }
        set {
            this.geometryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Fill")]
    public ShapeNodeFill Fill {
        get {
            return this.fillField;
        }
        set {
            this.fillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BorderStyle")]
    public ShapeNodeBorderStyle BorderStyle {
        get {
            return this.borderStyleField;
        }
        set {
            this.borderStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NodeLabel")]
    public ShapeNodeNodeLabel NodeLabel {
        get {
            return this.nodeLabelField;
        }
        set {
            this.nodeLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Shape")]
    public ShapeNodeShape Shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class ShapeNodeGeometry {
    
    private string heightField;
    
    private string widthField;
    
    private string xField;
    
    private string yField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class ShapeNodeFill {
    
    private string colorField;
    
    private string transparentField;
    
    private string hasColorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transparent {
        get {
            return this.transparentField;
        }
        set {
            this.transparentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hasColor {
        get {
            return this.hasColorField;
        }
        set {
            this.hasColorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class ShapeNodeBorderStyle {
    
    private string colorField;
    
    private string typeField;
    
    private string widthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class ShapeNodeNodeLabel {
    
    private string textField;

    private ShapeNodeNodeLabelLabelModel labelModelField;
    
    private ShapeNodeNodeLabelModelParameter modelParameterField;
    
    private string alignmentField;
    
    private string autoSizePolicyField;
    
    private string fontFamilyField;
    
    private string fontSizeField;
    
    private string fontStyleField;
    
    private string hasBackgroundColorField;
    
    private string hasLineColorField;
    
    private string hasTextField;
    
    private string heightField;
    
    private string modelNameField;
    
    private string textColorField;
    
    private string visibleField;
    
    private string widthField;
    
    private string xField;
    
    private string yField;

    /// <remarks/>
    [System.Xml.Serialization.XmlText()]
    public string Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LabelModel", typeof(ShapeNodeNodeLabelLabelModel), IsNullable = false)]
    public ShapeNodeNodeLabelLabelModel LabelModel {
        get {
            return this.labelModelField;
        }
        set {
            this.labelModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ModelParameter", typeof(ShapeNodeNodeLabelModelParameter), IsNullable = false)]
    public ShapeNodeNodeLabelModelParameter ModelParameter {
        get {
            return this.modelParameterField;
        }
        set {
            this.modelParameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alignment {
        get {
            return this.alignmentField;
        }
        set {
            this.alignmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string autoSizePolicy {
        get {
            return this.autoSizePolicyField;
        }
        set {
            this.autoSizePolicyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontFamily {
        get {
            return this.fontFamilyField;
        }
        set {
            this.fontFamilyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontStyle {
        get {
            return this.fontStyleField;
        }
        set {
            this.fontStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hasBackgroundColor {
        get {
            return this.hasBackgroundColorField;
        }
        set {
            this.hasBackgroundColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hasLineColor {
        get {
            return this.hasLineColorField;
        }
        set {
            this.hasLineColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hasText {
        get {
            return this.hasTextField;
        }
        set {
            this.hasTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string modelName {
        get {
            return this.modelNameField;
        }
        set {
            this.modelNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string textColor {
        get {
            return this.textColorField;
        }
        set {
            this.textColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yworks.com/xml/graphml")]
public partial class ShapeNodeNodeLabelLabelModel
{
    private ShapeNodeNodeLabelLabelModelSmartNodeLabelModel smartNodeLabelModelField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SmartNodeLabelModel", typeof(ShapeNodeNodeLabelLabelModelSmartNodeLabelModel), IsNullable = false)]
    public ShapeNodeNodeLabelLabelModelSmartNodeLabelModel SmartNodeLabelModel
    {
        get
        {
            return this.smartNodeLabelModelField;
        }
        set
        {
            this.smartNodeLabelModelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class ShapeNodeNodeLabelLabelModelSmartNodeLabelModel {
    
    private string distanceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yworks.com/xml/graphml")]
public partial class ShapeNodeNodeLabelModelParameter
{
    private ShapeNodeNodeLabelModelParameterSmartNodeLabelModelParameter smartNodeLabelModelParameterField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SmartNodeLabelModelParameter", typeof(ShapeNodeNodeLabelModelParameterSmartNodeLabelModelParameter), IsNullable = false)]
    public ShapeNodeNodeLabelModelParameterSmartNodeLabelModelParameter SmartNodeLabelModelParameter
    {
        get
        {
            return this.smartNodeLabelModelParameterField;
        }
        set
        {
            this.smartNodeLabelModelParameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class ShapeNodeNodeLabelModelParameterSmartNodeLabelModelParameter {
    
    private string labelRatioXField;
    
    private string labelRatioYField;
    
    private string nodeRatioXField;
    
    private string nodeRatioYField;
    
    private string offsetXField;
    
    private string offsetYField;
    
    private string upXField;
    
    private string upYField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string labelRatioX {
        get {
            return this.labelRatioXField;
        }
        set {
            this.labelRatioXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string labelRatioY {
        get {
            return this.labelRatioYField;
        }
        set {
            this.labelRatioYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodeRatioX {
        get {
            return this.nodeRatioXField;
        }
        set {
            this.nodeRatioXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodeRatioY {
        get {
            return this.nodeRatioYField;
        }
        set {
            this.nodeRatioYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string offsetX {
        get {
            return this.offsetXField;
        }
        set {
            this.offsetXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string offsetY {
        get {
            return this.offsetYField;
        }
        set {
            this.offsetYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string upX {
        get {
            return this.upXField;
        }
        set {
            this.upXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string upY {
        get {
            return this.upYField;
        }
        set {
            this.upYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class ShapeNodeShape {
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.yworks.com/xml/graphml", IsNullable=false)]
public partial class PolyLineEdge {
    
    private PolyLineEdgePath pathField;
    
    private PolyLineEdgeLineStyle lineStyleField;
    
    private PolyLineEdgeArrows arrowsField;
    
    private PolyLineEdgeEdgeLabel edgeLabelField;
    
    private PolyLineEdgeBendStyle bendStyleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Path")]
    public PolyLineEdgePath Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LineStyle")]
    public PolyLineEdgeLineStyle LineStyle {
        get {
            return this.lineStyleField;
        }
        set {
            this.lineStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Arrows")]
    public PolyLineEdgeArrows Arrows {
        get {
            return this.arrowsField;
        }
        set {
            this.arrowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EdgeLabel")]
    public PolyLineEdgeEdgeLabel EdgeLabel {
        get {
            return this.edgeLabelField;
        }
        set {
            this.edgeLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BendStyle")]
    public PolyLineEdgeBendStyle BendStyle {
        get {
            return this.bendStyleField;
        }
        set {
            this.bendStyleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class PolyLineEdgePath {
    
    private string sxField;
    
    private string syField;
    
    private string txField;
    
    private string tyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sx {
        get {
            return this.sxField;
        }
        set {
            this.sxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sy {
        get {
            return this.syField;
        }
        set {
            this.syField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tx {
        get {
            return this.txField;
        }
        set {
            this.txField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ty {
        get {
            return this.tyField;
        }
        set {
            this.tyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class PolyLineEdgeLineStyle {
    
    private string colorField;
    
    private string typeField;
    
    private string widthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class PolyLineEdgeArrows {
    
    private string sourceField;
    
    private string targetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class PolyLineEdgeEdgeLabel {

    private string textField;

    private string hasTextField;

    private PolyLineEdgeEdgeLabelPreferredPlacementDescriptor preferredPlacementDescriptorField;
    
    private string alignmentField;
    
    private string backgroundColorField;
    
    private string configurationField;
    
    private string distanceField;
    
    private string fontFamilyField;
    
    private string fontSizeField;
    
    private string fontStyleField;
    
    private string hasLineColorField;
    
    private string heightField;
    
    private string modelNameField;
    
    private string modelPositionField;
    
    private string preferredPlacementField;
    
    private string ratioField;
    
    private string textColorField;
    
    private string visibleField;
    
    private string widthField;
    
    private string xField;
    
    private string yField;

    /// <remarks/>
    [System.Xml.Serialization.XmlText()]
    public string Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hasText
    {
        get
        {
            return this.hasTextField;
        }
        set
        {
            this.hasTextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PreferredPlacementDescriptor")]
    public PolyLineEdgeEdgeLabelPreferredPlacementDescriptor PreferredPlacementDescriptor {
        get {
            return this.preferredPlacementDescriptorField;
        }
        set {
            this.preferredPlacementDescriptorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alignment {
        get {
            return this.alignmentField;
        }
        set {
            this.alignmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string backgroundColor {
        get {
            return this.backgroundColorField;
        }
        set {
            this.backgroundColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string configuration {
        get {
            return this.configurationField;
        }
        set {
            this.configurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontFamily {
        get {
            return this.fontFamilyField;
        }
        set {
            this.fontFamilyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontStyle {
        get {
            return this.fontStyleField;
        }
        set {
            this.fontStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hasLineColor {
        get {
            return this.hasLineColorField;
        }
        set {
            this.hasLineColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string modelName {
        get {
            return this.modelNameField;
        }
        set {
            this.modelNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string modelPosition {
        get {
            return this.modelPositionField;
        }
        set {
            this.modelPositionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string preferredPlacement {
        get {
            return this.preferredPlacementField;
        }
        set {
            this.preferredPlacementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ratio {
        get {
            return this.ratioField;
        }
        set {
            this.ratioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string textColor {
        get {
            return this.textColorField;
        }
        set {
            this.textColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class PolyLineEdgeEdgeLabelPreferredPlacementDescriptor {
    
    private string angleField;
    
    private string angleOffsetOnRightSideField;
    
    private string angleReferenceField;
    
    private string angleRotationOnRightSideField;
    
    private string distanceField;
    
    private string placementField;
    
    private string sideField;
    
    private string sideReferenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string angle {
        get {
            return this.angleField;
        }
        set {
            this.angleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string angleOffsetOnRightSide {
        get {
            return this.angleOffsetOnRightSideField;
        }
        set {
            this.angleOffsetOnRightSideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string angleReference {
        get {
            return this.angleReferenceField;
        }
        set {
            this.angleReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string angleRotationOnRightSide {
        get {
            return this.angleRotationOnRightSideField;
        }
        set {
            this.angleRotationOnRightSideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placement {
        get {
            return this.placementField;
        }
        set {
            this.placementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string side {
        get {
            return this.sideField;
        }
        set {
            this.sideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sideReference {
        get {
            return this.sideReferenceField;
        }
        set {
            this.sideReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yworks.com/xml/graphml")]
public partial class PolyLineEdgeBendStyle {
    
    private string smoothedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string smoothed {
        get {
            return this.smoothedField;
        }
        set {
            this.smoothedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://graphml.graphdrawing.org/xmlns", IsNullable=false)]
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
public partial class graphml {
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.

    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("data", typeof(data))]
    [System.Xml.Serialization.XmlElementAttribute("graph", typeof(graphmlGraph))]
    [System.Xml.Serialization.XmlElementAttribute("key", typeof(graphmlKey))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
public partial class graphmlGraph {
    
    private data[] dataField;
    
    private graphmlGraphNode[] nodeField;
    
    private graphmlGraphEdge[] edgeField;
    
    private string edgedefaultField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("data")]
    public data[] data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("node")]
    public graphmlGraphNode[] node {
        get {
            return this.nodeField;
        }
        set {
            this.nodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("edge")]
    public graphmlGraphEdge[] edge {
        get {
            return this.edgeField;
        }
        set {
            this.edgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string edgedefault {
        get {
            return this.edgedefaultField;
        }
        set {
            this.edgedefaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
public partial class graphmlGraphNode {
    
    private data dataField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("data")]
    public data data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
public partial class graphmlGraphEdge {
    
    private data dataField;
    
    private string idField;
    
    private string sourceField;
    
    private string targetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("data")]
    public data data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
public partial class graphmlKey {
    
    private string attrnameField;
    
    private string attrtypeField;
    
    private string forField;
    
    private string idField;
    
    private string yfilestypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("attr.name")]
    public string attrname {
        get {
            return this.attrnameField;
        }
        set {
            this.attrnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("attr.type")]
    public string attrtype {
        get {
            return this.attrtypeField;
        }
        set {
            this.attrtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @for {
        get {
            return this.forField;
        }
        set {
            this.forField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("yfiles.type")]
    public string yfilestype {
        get {
            return this.yfilestypeField;
        }
        set {
            this.yfilestypeField = value;
        }
    }
}
