//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Client.ProjectPlan.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Client.ProjectPlan.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mpp.
        /// </summary>
        public static string Filter_ImportMicrosoftProjectFileExtension {
            get {
                return ResourceManager.GetString("Filter_ImportMicrosoftProjectFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Projects.
        /// </summary>
        public static string Filter_ImportMicrosoftProjectFileType {
            get {
                return ResourceManager.GetString("Filter_ImportMicrosoftProjectFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .zpp.
        /// </summary>
        public static string Filter_OpenProjectPlanFileExtension {
            get {
                return ResourceManager.GetString("Filter_OpenProjectPlanFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Filter_OpenProjectPlanFileType {
            get {
                return ResourceManager.GetString("Filter_OpenProjectPlanFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv.
        /// </summary>
        public static string Filter_SaveCsvFileExtension {
            get {
                return ResourceManager.GetString("Filter_SaveCsvFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string Filter_SaveCsvFileType {
            get {
                return ResourceManager.GetString("Filter_SaveCsvFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .graphml.
        /// </summary>
        public static string Filter_SaveGraphMLFileExtension {
            get {
                return ResourceManager.GetString("Filter_SaveGraphMLFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphML.
        /// </summary>
        public static string Filter_SaveGraphMLFileType {
            get {
                return ResourceManager.GetString("Filter_SaveGraphMLFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .zpp.
        /// </summary>
        public static string Filter_SaveProjectPlanFileExtension {
            get {
                return ResourceManager.GetString("Filter_SaveProjectPlanFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Filter_SaveProjectPlanFileType {
            get {
                return ResourceManager.GetString("Filter_SaveProjectPlanFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Label_ActivitiesViewTitle {
            get {
                return ResourceManager.GetString("Label_ActivitiesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Name.
        /// </summary>
        public static string Label_ActivityName {
            get {
                return ResourceManager.GetString("Label_ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Risk:.
        /// </summary>
        public static string Label_ActivityRisk {
            get {
                return ResourceManager.GetString("Label_ActivityRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity (Std Dev) Risk:.
        /// </summary>
        public static string Label_ActivityRiskWithStdDevCorrection {
            get {
                return ResourceManager.GetString("Label_ActivityRiskWithStdDevCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Label_AddManagedActivity {
            get {
                return ResourceManager.GetString("Label_AddManagedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Label_AddManagedResource {
            get {
                return ResourceManager.GetString("Label_AddManagedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated Resources.
        /// </summary>
        public static string Label_AllocatedResources {
            get {
                return ResourceManager.GetString("Label_AllocatedResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Plan.
        /// </summary>
        public static string Label_AppName {
            get {
                return ResourceManager.GetString("Label_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 0.4.0-alpha.
        /// </summary>
        public static string Label_AppVersion {
            get {
                return ResourceManager.GetString("Label_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph....
        /// </summary>
        public static string Label_ArrowGraphSettings {
            get {
                return ResourceManager.GetString("Label_ArrowGraphSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph.
        /// </summary>
        public static string Label_ArrowGraphViewTitle {
            get {
                return ResourceManager.GetString("Label_ArrowGraphViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Compile.
        /// </summary>
        public static string Label_AutoCompile {
            get {
                return ResourceManager.GetString("Label_AutoCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Label_Close {
            get {
                return ResourceManager.GetString("Label_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Label_Color {
            get {
                return ResourceManager.GetString("Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string Label_Compile {
            get {
                return ResourceManager.GetString("Label_Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart to Clipboard.
        /// </summary>
        public static string Label_CopyEarnedValueChartToClipboard {
            get {
                return ResourceManager.GetString("Label_CopyEarnedValueChartToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart to Clipboard.
        /// </summary>
        public static string Label_CopyResourceChartToClipboard {
            get {
                return ResourceManager.GetString("Label_CopyResourceChartToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2018, Riccardo M Bennett-Lovsey.
        /// </summary>
        public static string Label_Copyright {
            get {
                return ResourceManager.GetString("Label_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticality Risk:.
        /// </summary>
        public static string Label_CriticalityRisk {
            get {
                return ResourceManager.GetString("Label_CriticalityRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit. Weight.
        /// </summary>
        public static string Label_CriticalityWeight {
            get {
                return ResourceManager.GetString("Label_CriticalityWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic Complexity:.
        /// </summary>
        public static string Label_CyclomaticComplexity {
            get {
                return ResourceManager.GetString("Label_CyclomaticComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Label_DefaultTitle {
            get {
                return ResourceManager.GetString("Label_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Unit Cost:.
        /// </summary>
        public static string Label_DefaultUnitCost {
            get {
                return ResourceManager.GetString("Label_DefaultUnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_DeleteManagedActivity {
            get {
                return ResourceManager.GetString("Label_DeleteManagedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_DeleteManagedResource {
            get {
                return ResourceManager.GetString("Label_DeleteManagedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Label_Dependencies {
            get {
                return ResourceManager.GetString("Label_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Cost:.
        /// </summary>
        public static string Label_DirectCost {
            get {
                return ResourceManager.GetString("Label_DirectCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Resources:.
        /// </summary>
        public static string Label_DisableResources {
            get {
                return ResourceManager.GetString("Label_DisableResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string Label_DisplayOrder {
            get {
                return ResourceManager.GetString("Label_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Label_Documentation {
            get {
                return ResourceManager.GetString("Label_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Label_Duration {
            get {
                return ResourceManager.GetString("Label_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (months):.
        /// </summary>
        public static string Label_DurationManMonths {
            get {
                return ResourceManager.GetString("Label_DurationManMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFT.
        /// </summary>
        public static string Label_EarliestFinishTime {
            get {
                return ResourceManager.GetString("Label_EarliestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EST.
        /// </summary>
        public static string Label_EarliestStartTime {
            get {
                return ResourceManager.GetString("Label_EarliestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned Value Chart.
        /// </summary>
        public static string Label_EarnedValueChartsViewTitle {
            get {
                return ResourceManager.GetString("Label_EarnedValueChartsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned Value (%).
        /// </summary>
        public static string Label_EarnedValuePercentageAxisTitle {
            get {
                return ResourceManager.GetString("Label_EarnedValuePercentageAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned Value.
        /// </summary>
        public static string Label_EarnedValueTitle {
            get {
                return ResourceManager.GetString("Label_EarnedValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit Target.
        /// </summary>
        public static string Label_ExplicitTarget {
            get {
                return ResourceManager.GetString("Label_ExplicitTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To CSV.
        /// </summary>
        public static string Label_ExportEarnedValueChartToCsv {
            get {
                return ResourceManager.GetString("Label_ExportEarnedValueChartToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to GraphML.
        /// </summary>
        public static string Label_ExportGraphML {
            get {
                return ResourceManager.GetString("Label_ExportGraphML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as costs:.
        /// </summary>
        public static string Label_ExportResourceChartAsCosts {
            get {
                return ResourceManager.GetString("Label_ExportResourceChartAsCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To CSV.
        /// </summary>
        public static string Label_ExportResourceChartToCsv {
            get {
                return ResourceManager.GetString("Label_ExportResourceChartToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci Risk:.
        /// </summary>
        public static string Label_FibonacciRisk {
            get {
                return ResourceManager.GetString("Label_FibonacciRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fib. Weight.
        /// </summary>
        public static string Label_FibonacciWeight {
            get {
                return ResourceManager.GetString("Label_FibonacciWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Label_File {
            get {
                return ResourceManager.GetString("Label_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FS.
        /// </summary>
        public static string Label_FreeSlack {
            get {
                return ResourceManager.GetString("Label_FreeSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Arrow Graph.
        /// </summary>
        public static string Label_GenerateArrowGraph {
            get {
                return ResourceManager.GetString("Label_GenerateArrowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric (Act.) Risk:.
        /// </summary>
        public static string Label_GeometricActivityRisk {
            get {
                return ResourceManager.GetString("Label_GeometricActivityRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric (Crit.) Risk:.
        /// </summary>
        public static string Label_GeometricCriticalityRisk {
            get {
                return ResourceManager.GetString("Label_GeometricCriticalityRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric (Fib.) Risk:.
        /// </summary>
        public static string Label_GeometricFibonacciRisk {
            get {
                return ResourceManager.GetString("Label_GeometricFibonacciRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string Label_Height {
            get {
                return ResourceManager.GetString("Label_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Label_Help {
            get {
                return ResourceManager.GetString("Label_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Label_Id {
            get {
                return ResourceManager.GetString("Label_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string Label_Import {
            get {
                return ResourceManager.GetString("Label_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Cost:.
        /// </summary>
        public static string Label_IndirectCost {
            get {
                return ResourceManager.GetString("Label_IndirectCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter-activity Allocation.
        /// </summary>
        public static string Label_InterActivityAllocation {
            get {
                return ResourceManager.GetString("Label_InterActivityAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS.
        /// </summary>
        public static string Label_InterferingSlack {
            get {
                return ResourceManager.GetString("Label_InterferingSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        public static string Label_InvalidFormat {
            get {
                return ResourceManager.GetString("Label_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string Label_IsCritical {
            get {
                return ResourceManager.GetString("Label_IsCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy.
        /// </summary>
        public static string Label_IsDummy {
            get {
                return ResourceManager.GetString("Label_IsDummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LFT.
        /// </summary>
        public static string Label_LatestFinishTime {
            get {
                return ResourceManager.GetString("Label_LatestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LST.
        /// </summary>
        public static string Label_LatestStartTime {
            get {
                return ResourceManager.GetString("Label_LatestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Label_Max {
            get {
                return ResourceManager.GetString("Label_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum EST.
        /// </summary>
        public static string Label_MinimumEarliestStartTime {
            get {
                return ResourceManager.GetString("Label_MinimumEarliestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum FS.
        /// </summary>
        public static string Label_MinimumFreeSlack {
            get {
                return ResourceManager.GetString("Label_MinimumFreeSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Label_Ok {
            get {
                return ResourceManager.GetString("Label_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string Label_Open {
            get {
                return ResourceManager.GetString("Label_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Cost:.
        /// </summary>
        public static string Label_OtherCost {
            get {
                return ResourceManager.GetString("Label_OtherCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Start:.
        /// </summary>
        public static string Label_ProjectStart {
            get {
                return ResourceManager.GetString("Label_ProjectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string Label_ReportIssue {
            get {
                return ResourceManager.GetString("Label_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Graph.
        /// </summary>
        public static string Label_ResetGraph {
            get {
                return ResourceManager.GetString("Label_ResetGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Chart.
        /// </summary>
        public static string Label_ResourceChartsViewTitle {
            get {
                return ResourceManager.GetString("Label_ResourceChartsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Dependencies.
        /// </summary>
        public static string Label_ResourceDependencies {
            get {
                return ResourceManager.GetString("Label_ResourceDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Name.
        /// </summary>
        public static string Label_ResourceName {
            get {
                return ResourceManager.GetString("Label_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Label_ResourcesAxisTitle {
            get {
                return ResourceManager.GetString("Label_ResourcesAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources....
        /// </summary>
        public static string Label_ResourceSettings {
            get {
                return ResourceManager.GetString("Label_ResourceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        public static string Label_Save {
            get {
                return ResourceManager.GetString("Label_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self dependency.
        /// </summary>
        public static string Label_SelfDependency {
            get {
                return ResourceManager.GetString("Label_SelfDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Label_Settings {
            get {
                return ResourceManager.GetString("Label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Dates.
        /// </summary>
        public static string Label_ShowDates {
            get {
                return ResourceManager.GetString("Label_ShowDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slack Limit.
        /// </summary>
        public static string Label_SlackLimit {
            get {
                return ResourceManager.GetString("Label_SlackLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Operator.
        /// </summary>
        public static string Label_TargetResourceOperator {
            get {
                return ResourceManager.GetString("Label_TargetResourceOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Resources.
        /// </summary>
        public static string Label_TargetResources {
            get {
                return ResourceManager.GetString("Label_TargetResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Label_TimeAxisTitle {
            get {
                return ResourceManager.GetString("Label_TimeAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost:.
        /// </summary>
        public static string Label_TotalCost {
            get {
                return ResourceManager.GetString("Label_TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS.
        /// </summary>
        public static string Label_TotalSlack {
            get {
                return ResourceManager.GetString("Label_TotalSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transitive Reduction.
        /// </summary>
        public static string Label_TransitiveReduction {
            get {
                return ResourceManager.GetString("Label_TransitiveReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string Label_UnitCost {
            get {
                return ResourceManager.GetString("Label_UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Business Days.
        /// </summary>
        public static string Label_UseBusinessDays {
            get {
                return ResourceManager.GetString("Label_UseBusinessDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License.
        /// </summary>
        public static string Label_ViewLicense {
            get {
                return ResourceManager.GetString("Label_ViewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string Label_Width {
            get {
                return ResourceManager.GetString("Label_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/countincognito/Zametek.ProjectPlan/wiki.
        /// </summary>
        public static string Link_Documentation {
            get {
                return ResourceManager.GetString("Link_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/countincognito/Zametek.ProjectPlan/issues.
        /// </summary>
        public static string Link_ReportIssue {
            get {
                return ResourceManager.GetString("Link_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/countincognito/Zametek.ProjectPlan/blob/master/LICENSE.
        /// </summary>
        public static string Link_ViewLicense {
            get {
                return ResourceManager.GetString("Link_ViewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All resources are explicit targets, but not all activities have targeted resources.
        /// </summary>
        public static string Message_AllResourcesExplicitTargetsNotAllActivitiesTargeted {
            get {
                return ResourceManager.GetString("Message_AllResourcesExplicitTargetsNotAllActivitiesTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular activity dependencies:.
        /// </summary>
        public static string Message_CircularDependencies {
            get {
                return ResourceManager.GetString("Message_CircularDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation errors.
        /// </summary>
        public static string Message_CompilationErrors {
            get {
                return ResourceManager.GetString("Message_CompilationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty filename.
        /// </summary>
        public static string Message_EmptyFilename {
            get {
                return ResourceManager.GetString("Message_EmptyFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing activity dependencies:.
        /// </summary>
        public static string Message_MissingDependencies {
            get {
                return ResourceManager.GetString("Message_MissingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has unsaved changes. Do you wish to continue?.
        /// </summary>
        public static string Message_UnsavedChanges {
            get {
                return ResourceManager.GetString("Message_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Plan.
        /// </summary>
        public static string Title_AppName {
            get {
                return ResourceManager.GetString("Title_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Graph Settings.
        /// </summary>
        public static string Title_ArrowGraphSettings {
            get {
                return ResourceManager.GetString("Title_ArrowGraphSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Settings.
        /// </summary>
        public static string Title_ResourceSettings {
            get {
                return ResourceManager.GetString("Title_ResourceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has unsaved changes.
        /// </summary>
        public static string Title_UnsavedChanges {
            get {
                return ResourceManager.GetString("Title_UnsavedChanges", resourceCulture);
            }
        }
    }
}
